- ui/test/unit/registration/mappers/createPatientRequestMapper.spec.js
- ui/test/unit/registration/mappers/openmrsPatientMapper.spec.js
Hi all, small fix to the tests (removed hard coded IST timezone)
> Fixing test when run in timezone other than IST

- ui/test/unit/clinical/controllers/drugOrderHistoryController.spec.js
This date actually works out to "Sep 09 2014 21:17:04 GMT-0700 (PDT)" when I run this test in Seattle
> Fix test to run successfully on Pacific time

- .tx/config
Adding transifex configuration for the tx client
> adding transifex config

- ui/app/registration/controllers/visitController.js
- ui/test/unit/registration/controllers/visitController.spec.js
This is an updated pull request with squashed commits based on feedback on:
https://github.com/Bahmni/openmrs-module-bahmniapps/pull/21
> 1755: Ability to configure forward-url on click of Save on Registration visit page

- ui/app/common/uicontrols/programmanagement/controllers/manageProgramController.js
See:  https://talk.openmrs.org/t/bahmniapps-2-tests-failing-in-the-release-0-81-branch/6589
> Fix timezone related error in date comparison function.

- .travis.yml
- README.md
Travis .yml build with no notifications
> Adding travis yml

- ui/app/clinical/common/views/visitTabPrint.html
- ui/app/clinical/dashboard/views/dashboardPrint.html
This is to avoid one dummy call from browser using AngularJS expression
as literal
> Replaced image src by ng-src

- ui/app/adt/app.js
- ui/app/adt/index.html
- ui/app/i18n/adt/locale_en.json
Support ConditionsList displayControl in ADT dashboard
> Support ConditionsList displayControl in ADT dashboard

- ui/app/admin/views/auditLog.html
https://trello.com/c/mYscHfzS/89-on-pressing-the-enter-key-in-any-filter-field-the-audit-log-filter-button-should-get-pressed
> Any field in Audit Log filter filters when ENTER key is pressed

- ui/app/home/views/dashboard.html
- ui/app/home/views/login.html
- ui/app/registration/views/header.html
modified:   app/home/views/dashboard.html
modified:   app/home/views/login.html
modified:   app/registration/views/header.html
> TLC-20: Translating the location on various screens.

- ui/app/common/domain/services/localeService.js
- ui/app/home/controllers/loginController.js
- ui/test/unit/home/controllers/loginController.spec.js
modified:   app/common/domain/services/localeService.js
modified:   app/home/controllers/loginController.js
modified:   test/unit/home/controllers/loginController.spec.js
> BAH-329: Setting the backend locale upon user login.

- ui/app/registration/views/addressFields.html
modified:   app/registration/views/addressFields.html
> BAH-311 | Allow localisation of address fields

- ui/app/registration/models/identifier.js
- ui/test/unit/registration/models/identifier.spec.js
See JIRA issue description:
https://bahmni.atlassian.net/browse/BAH-376
> rbuisson | BAH-376 | Consider 'null' identifier sources prefix as empty

- ui/app/i18n/appointments/locale_en.json
- ui/app/i18n/appointments/locale_es.json
- ui/app/i18n/appointments/locale_fr.json
- ui/app/i18n/appointments/locale_pt_BR.json
[Improve error message for invalid start/end times](https://bahmni.atlassian.net/browse/BAH-482?src=confmacro)
> BAH-482|Improve error message for invalid start/end times

- ui/app/appointments/directives/datePicker.js
- ui/app/appointments/views/manage/calendar/calendarView.html
- ui/app/appointments/views/manage/list/listView.html
- ui/test/unit/appointments/directives/datePicker.spec.js
BAH-435 Date picker date in appointment list/calendar view can be cleared with the delete button
> BAH-435 Date picker date in appointment list/calendar view can be cleared with the delete button

- ui/app/clinical/displaycontrols/graph/views/observationGraph.html
See details in JIRA issue comment: https://bahmni.atlassian.net/browse/BAH-311?focusedCommentId=11758&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-11758
> BAH-311: L10n support for the 'observationGraph' display control

- ui/app/common/util/init.js
- ui/test/unit/common/util/init.spec.js
JIRA id:
https://bahmni.atlassian.net/browse/BAH-398
> BAH-398 | [Fix] Causes error If value for a key is undefined in Cookie

- ui/app/common/domain/mappers/patientProgramMapper.js
- ui/test/unit/common/domain/mappers/patientProgramMapper.spec.js
https://bahmni.atlassian.net/browse/BAH-529
> BAH-529 | Sending date without time for fixing program enrollement issue

- ui/app/document-upload/controllers/documentController.js
- ui/app/document-upload/views/documentUpload.html
Read all Patient Document set members and displayed it in drop down as document file type.
Code was changed for populating this drop down and after selection change setting appropriate selected file type with uploaded file.
> https://bahmni.atlassian.net/browse/BAH-465

- ui/app/registration/controllers/visitController.js
Added condition for Mandatory Boolean Concept on Visit Page as explained
https://talk.openmrs.org/t/error-while-saving-visit-page-with-mandatory-boolean-concept/14967
> BAH-415 Mandatory Boolean Concept on Visit Page 

- ui/app/common/concept-set/directives/imageUpload.js
Just had to make 1 modification to get the Form to save when an Image is set to Mandatory.
Here is the JIRA Card:
https://bahmni.atlassian.net/browse/BAH-446
The reason why the problem was occurring is mentioned in the JIRA Card
> Bah 446: Form is not saved when concept of Image type is marked as Mandatory 

- ui/app/clinical/displaycontrols/investigationresults/views/investigationChart.html
- ui/app/styles/clinical/_program.scss
Made investigation chart title sticky with respect to dialog's vertical and horizontal scroll.
Also made test names and date labels sticky too.
> https://bahmni.atlassian.net/browse/BAH-495

- ui/Gruntfile.js
- ui/app/ot/index.html
Added missing library to gruntfile and using moment-with-locales.min.js instead of moment.min.js
> BAH-489 | Add missing library

- ui/Gruntfile.js
- ui/app/bedmanagement/index.html
Currently, `grunt` is not creating **bedmanagement** folder in dist folder, as a result of this bedmanagement is not running. These are the changes to resolve this.
> BAH-515 | Create bedmanagement in dist

- ui/app/registration/controllers/patientCommonController.js
- ui/test/unit/registration/controllers/patientCommonController.spec.js
Solved the problem of the Prompt appearing on "Enter Visit Details" page
> BAH-497: Prompt to save if home or search clicked in registration screen

- ui/app/ot/views/surgicalBlock.html
Reverts Bahmni/openmrs-module-bahmniapps#186
> Revert "BAH-599 | [FIX] Re-arranging appointments should not throw error"

- ui/app/appointments/directives/datePicker.js
- ui/app/appointments/views/manage/datePicker.html
- ui/test/unit/appointments/directives/datePicker.spec.js
date picker makes a single API call on change and on blur. Also delete and backspace will make a single API call on blur
> https://bahmni.atlassian.net/browse/BAH-435

- ui/test/unit/registration/controllers/visitController.spec.js
https://bahmni.atlassian.net/browse/BAH-195
> Shilpa | BAH-195 | test for should not call save twice for a visit

- ui/app/home/views/login.html
https://bahmni.atlassian.net/browse/BAH-612
> Shilpa | BAH-612

- ui/app/appointments/controllers/manage/calendar/appointmentsCalendarViewController.js
- ui/app/appointments/controllers/manage/list/appointmentsListViewController.js
- ui/test/unit/appointments/controllers/manage/calendar/appointmentsCalendarViewController.spec.js
- ui/test/unit/appointments/controllers/manage/list/appointmentsListViewController.spec.js
[JIRA link for Auto Refresh Story](https://bahmni.atlassian.net/browse/BAH-624)
Configuration:- 
We need to add a configuration to enable this feature. We have to configure with a time interval by providing value to `autoRefreshIntervalInSeconds` in ***openmrs/apps/appointments/app.json*** in config.
> Auto Refresh of Appointments

- ui/app/appointments/directives/patientSearch.js
- ui/test/unit/appointments/directives/patientSearch.spec.js
[JIRA CARD](https://bahmni.atlassian.net/browse/BAH-674)
> Avoid showing null in the family name in List View Patient Search

- ui/app/appointments/services/calendarViewPopUp.js
- ui/app/appointments/views/manage/calendar/popUp.html
- ui/test/unit/appointments/services/calendarViewPopUp.spec.js
Differentiate multiple appointments created in same slot for same patient in calendar view popup
[JIRA CARD](https://bahmni.atlassian.net/browse/BAH-670)
> Differentiate multiple appointments 

- ui/app/appointments/services/checkinPopUp.js
- ui/app/appointments/views/checkInPopUp.html
- ui/test/unit/appointments/services/checkinPopUp.spec.js
https://bahmni.atlassian.net/browse/BAH-668
> Neha | BAH-668 | Fix two way binding for appointment checkedIn time

- ui/app/clinical/index.html
- ui/app/common/constants.js
- ui/app/common/displaycontrols/dashboard/models/dashboardSection.js
- ui/app/common/displaycontrols/dashboard/views/sections/formsV2.html
- ui/app/common/displaycontrols/forms/controllers/versionedFormController.js
- ui/app/common/displaycontrols/forms/directives/formsTable.js
- ui/app/common/displaycontrols/forms/views/formsTable.html
- ui/app/common/services/formService.js
- ui/app/i18n/clinical/locale_en.json
- ui/test/unit/common/displaycontrols/forms/controllers/versionedFormController.spec.js
- ui/test/unit/common/displaycontrols/forms/directives/formsTable.spec.js
- ui/test/unit/common/services/formService.spec.js
1. Add service to fetch V2 forms
2. Add controller for forms2.0 display control
3. update REST_V1 url to BAHMNI_CORE
Notes: [PR](https://github.com/Bahmni/bahmni-core/pull/41) for bahmni-core should be merged before merging this PR
>  #BAH-693 | Forms display control for V2 forms

- ui/app/clinical/displaycontrols/investigationresults/views/investigationTableRow.html
Update format of showing provider and resultDateTime to maintain consistency with other display controls
https://bahmni.atlassian.net/browse/BAH-701
> BAH-701 | Show order results updated time in lab orders display control

- ui/app/ot/controller/calendarViewController.js
- ui/app/styles/adt/_adt.scss
- ui/app/styles/ot/_ot.scss
- ui/test/unit/ot/controller/calendarViewController.spec.js
OpenMRS Talk link: https://talk.openmrs.org/t/bahmni-patient-document-bug/21834
> Sneha Bagri | Bahmni Patient Document Bug

- ui/app/appointments/controllers/manage/appointmentsCreateController.js
- ui/test/unit/appointments/controllers/manage/appointmentsCreateController.spec.js
Change the time slot to service duration time slot when start time is edited for an appointment
[JIRA link](https://bahmni.atlassian.net/browse/BAH-771)
> Set time to service duration on edit of appointment(change start time)

- ui/app/common/patient-search/controllers/patientsListController.js
- ui/app/common/patient-search/views/patientsList.html
- ui/app/styles/clinical/_patientSearch.scss
- ui/test/unit/common/patient-search/controllers/patientsListController.spec.js
JIRA Link - https://bahmni.atlassian.net/browse/BAH-772
> Enhancement of Program Queues

- ui/app/appointments/constants.js
- ui/app/appointments/controllers/manage/allAppointmentsController.js
- ui/app/appointments/controllers/manage/appointmentsCreateController.js
- ui/app/appointments/controllers/manage/calendar/appointmentsDayCalendarController.js
- ui/app/appointments/controllers/manage/list/appointmentsListViewController.js
- ui/app/appointments/index.html
- ui/app/appointments/services/appointmentCommonService.js
- ui/app/appointments/services/calendarViewPopUp.js
- ui/app/appointments/views/manage/allAppointments.html
- ui/app/appointments/views/manage/calendar/popUp.html
- ui/app/appointments/views/manage/list/listView.html
- ui/app/appointments/views/manage/newAppointment.html
- ui/test/unit/appointments/controllers/manage/appointmentsCreateController.spec.js
- ui/test/unit/appointments/controllers/manage/calendar/appointmentsDayCalendarController.spec.js
- ui/test/unit/appointments/controllers/manage/list/appointmentsListViewController.spec.js
- ui/test/unit/appointments/services/appointmentCommonService.spec.js
- ui/test/unit/appointments/services/calendarViewPopUp.spec.js
https://bahmni.atlassian.net/browse/BAH-625
> BAH-625 | Add self privilege ui pr

- ui/app/common/patient-search/controllers/patientsListController.js
JIRA Link - https://bahmni.atlassian.net/browse/BAH-772
> #BAH-772 | Enhancement of Program Queues - Add null check

- ui/app/registration/controllers/createPatientController.js
- ui/test/unit/registration/controllers/createPatientController.spec.js
https://bahmni.atlassian.net/browse/BAH-747
> Sowmika | BAH-747 | Set current date as default for date type person attribute 

- ui/app/styles/bedmanagement/_bedmanagement.scss
Changed the CSS display property. 
Product jira card: https://bahmni.atlassian.net/browse/BAH-867
> #BAH-867 | UI layout fix for beds in bed management module

- ui/app/clinical/consultation/controllers/conceptSetPageController.js
- ui/app/common/concept-set/directives/conceptSetGroup.js
- ui/test/unit/common/concept-set/directives/conceptSetGroup.spec.js
Original template form's isAdded is made false so that it could be re-added again.
Also After second consecutive deletion and then addition for third time was causing issue in form addition in function addTemplate as code had that form already added. So fixed it.
> Shilpa|BAH-513|deleted Obs form can be readded

- ui/app/common/displaycontrols/dashboard/views/sections/observationSection.html
- ui/app/common/displaycontrols/observation/directives/bahmniObservation.js
- ui/app/common/displaycontrols/observation/services/formRecordTreeBuildService.js
- ui/app/common/displaycontrols/observation/views/allObservationDetails.html
- ui/test/unit/common/displaycontrols/observation/directives/bahmniObservation.spec.js
- ui/test/unit/common/displaycontrols/observation/services/formRecordTreeBuildService.spec.js
Find JIRA card: https://bahmni.atlassian.net/browse/BAH-909
> Messed Up Formatting for Forms 2.0 Concepts in Obs Display Controls

- ui/app/common/patient-search/controllers/patientsListController.js
See: https://bahmni.atlassian.net/browse/BAH-956
> Use classname instead of relying on position of the patient list spinner

- ui/app/appointments/controllers/manage/list/appointmentsListViewController.js
[BAH-959](https://bahmni.atlassian.net/browse/BAH-959)
> BAH-959 | Sowmika | Deselect the selected appointment when we move from list view to patient search

- ui/app/appointments/controllers/manage/appointmentsManageController.js
- ui/test/unit/appointments/controllers/manage/appointmentsManageController.spec.js
[BAH-960](https://bahmni.atlassian.net/browse/BAH-960)
> BAH-960 | Sowmika | Fix changing to calendar day view always when clicking on AppointmentList Tab

- ui/app/reports/views/reports.html
Added show-if-privilege check in report list render loop
> BAH 395 - Added Role based access for individual report - ui end 

- ui/app/bedmanagement/views/admitConfirmation.html
- ui/app/bedmanagement/views/dischargeConfirmation.html
- ui/app/bedmanagement/views/transferConfirmation.html
- ui/app/i18n/ipd/locale_en.json
[BAH-969](https://bahmni.atlassian.net/browse/BAH-969)
> BAH-969 | Sowmika | MOBN-609 | Change text to keys for admit, movement and discharge popups in bedmanagement

- ui/app/registration/controllers/searchPatientController.js
- ui/app/registration/views/search.html
https://bahmni.atlassian.net/browse/BAH-521
> BAH-521 | Fill L10n gaps

- ui/app/adt/index.html
- ui/app/bedmanagement/services/bedManagementService.js
- ui/app/styles/bedmanagement/_bedmanagement.scss
- ui/test/unit/bedmanagement/services/bedManagementService.spec.js
JIRA Link - https://bahmni.atlassian.net/browse/BAH-970
> BAH-970 | ADT module shows an error message on load 

- ui/app/document-upload/views/documentUpload.html
- ui/app/i18n/document-upload/locale_en.json
https://bahmni.atlassian.net/browse/BAH-984
> BAH-984: Support l10n for Patient Documents app

- ui/app/common/concept-set/views/conceptSetGroupSection.html
- ui/app/styles/clinical/_observations.scss
[BAH-1005](https://bahmni.atlassian.net/browse/BAH-1005)
> BAH-1005 | UI Fixes

- ui/app/common/domain/services/encounterService.js
After the commit - https://github.com/twhyderabad/openmrs-module-bahmniapps/commit/66c95f6f6e386e34a4affca770810bd61d592cff, we get an error on dashboard for few display controls which allow edit of forms (Form2) after being filled eg Obs to Obs flowsheet etc.
> Sneha| BAH-1012 | Fix Cannot read property 'map' of undefined error

- ui/app/clinical/consultation/controllers/consultationController.js
- ui/app/common/concept-set/directives/formControls.js
Jira link: https://bahmni.atlassian.net/browse/BAH-1009
this pr has dependency on [form controls pr](https://github.com/Bahmni/form-controls/pull/22), please merge this after that pr.
> BAH-1009 | Alekhya, Yamuna | Execute the onFormSave event when form save is clicked in consultation

- ui/Gruntfile.js
- ui/app/clinical/index.html
- ui/bower.json
- ui/package-lock.json
- ui/package.json
This depends on. - https://github.com/Bahmni/form-controls/pull/21. The build will fail until this is merged and published.
> Sneha Bagri | BAH-754 | Upgrade the react version to 16

- ui/app/clinical/consultation/controllers/consultationController.js
- ui/app/common/concept-set/models/observationForm.js
- ui/test/unit/clinical/models/observationForm.spec.js
https://bahmni.atlassian.net/browse/BAH-1019
> BAH-1019 | Sowmika, Alekhya  | Consultation bug fix

- ui/app/clinical/consultation/controllers/consultationController.js
- ui/app/styles/common/_notifications.scss
- ui/test/unit/clinical/controllers/consultationController.spec.js
https://bahmni.atlassian.net/browse/BAH-1017
> BAH-1017 | Preview and onSave event error handling 

- ui/app/common/concept-set/directives/formControls.js
Backend PR - https://github.com/Bahmni/openmrs-module-bahmni.ie.apps/pull/12
> BAH-1018| Use form UUID as translation file and form file name

- ui/app/clinical/consultation/controllers/conceptSetPageController.js
- ui/app/common/concept-set/models/observationForm.js
- ui/app/common/displaycontrols/forms/controllers/versionedFormController.js
- ui/app/common/displaycontrols/observation/directives/bahmniObservation.js
- ui/app/common/displaycontrols/observation/services/formRecordTreeBuildService.js
- ui/app/common/displaycontrols/observation/views/observationDisplayControl.html
- ui/app/common/obs/directives/editObservation.js
- ui/app/common/obs/views/editObservation.html
- ui/app/common/services/formService.js
- ui/app/registration/controllers/visitController.js
- ui/package-lock.json
- ui/package.json
- ui/test/unit/clinical/consultation/controllers/conceptSetPageController.spec.js
- ui/test/unit/clinical/models/observationForm.spec.js
- ui/test/unit/common/displaycontrols/forms/controllers/versionedFormController.spec.js
- ui/test/unit/common/displaycontrols/forms/directives/formsTable.spec.js
- ui/test/unit/common/displaycontrols/observation/services/formRecordTreeBuildService.spec.js
Backend PR- https://github.com/Bahmni/openmrs-module-bahmni.ie.apps/pull/13
> BAH-936 | Form name translations with Forms 2.0

- ui/app/reports/views/reports.html
Reports names can now be configured in `bahmni_config/openmrs/apps/reports/reports.json ` as i18n message keys
> BAH-521: Adding ability to translate report names

- ui/app/bedmanagement/constants.js
- ui/app/common/domain/services/encounterService.js
https://bahmni.atlassian.net/browse/BAH-885
After Bahmni EMR upgrade (v.91) we lost the ability to edit bed tags]
> BAH-885 | Edit bed tags privilege fix

- ui/app/document-upload/views/documentUpload.html
JIRA link: https://bahmni.atlassian.net/browse/BAH-1088
> Vinisha | BAH-1088 | Add missing closing brace in document upload

- ui/app/registration/index.html
JIRA link: https://bahmni.atlassian.net/browse/BAH-1089
> Bindu | BAH-1089 | Add require dependencies to render form2 forms in registration second page

- ui/app/registration/views/patientcommon.html
This label will only show if address fields are defined
https://monosnap.com/direct/nV17dNIYzMmJoIorYL87hLCwviQGNX 
JIRA link: https://bahmni.atlassian.net/browse/BAH-1087
> michael | BAH-1087 | Making the "Address information" section label dynamic in the registration page

- ui/app/appointments/controllers/manage/list/appointmentsListViewController.js
- ui/app/appointments/views/manage/list/defaultListPrint.html
- ui/app/appointments/views/manage/list/listView.html
- ui/test/unit/appointments/controllers/manage/list/appointmentsListViewController.spec.js
> BAH-675|Buvaneswari|Show Language of the patient in List View, Appointments Module

- ui/app/common/obs/views/showObservation.html
https://bahmni.atlassian.net/browse/BAH-1130
> Supriya | MOBN-1067 | BAH-1130 | Wrap the text for free text fields in editforms 2.0 display controls and observations

- ui/app/styles/registration/_registration.scss
https://bahmni.atlassian.net/browse/BAH-1089
> Bindu | BAH-1089 | [Forms 2]Text fields are misaligned in registration second page

- ui/app/clinical/consultation/services/treatmentConfig.js
https://bahmni.atlassian.net/browse/BAH-1194
> BAH-1194 | Remove hardcoded duration units

- ui/app/i18n/ot/locale_en.json
- ui/app/ot/controller/calendarViewController.js
- ui/app/ot/views/home.html
- ui/test/unit/ot/controller/calendarViewController.spec.js
https://bahmni.atlassian.net/browse/BAH-1188
> Tarun | BAH-1188 | Apply filters dynamically on the Calendar/List view of OT Scheduling module

- ui/app/bedmanagement/controllers/adtController.js
- ui/test/unit/bedmanagement/controllers/adtController.spec.js
Bahmni Card - https://bahmni.atlassian.net/browse/BAH-1189
> Tarun, Venky | BAH-1189 | Fix issues related to multiple clicks while admitting, transferring and discharging

- ui/app/i18n/ot/locale_en.json
- ui/app/ot/controller/calendarViewController.js
- ui/app/ot/controller/listViewController.js
- ui/app/ot/controller/otCalendarController.js
- ui/app/ot/controller/surgicalBlockController.js
- ui/app/ot/directives/otCalendarSurgicalAppointment.js
- ui/app/ot/directives/otCalendarSurgicalBlock.js
- ui/app/ot/services/surgicalAppointmentService.js
- ui/app/ot/views/addActualTimeDialog.html
- ui/app/ot/views/calendarSurgicalBlock.html
- ui/app/ot/views/otCalendar.html
- ui/app/ot/views/otWeeklyCalendar.html
- ui/app/ot/views/surgicalAppointmentDialog.html
- ui/app/ot/views/surgicalBlockDialog.html
- ui/app/ot/views/surgicalBlockMultipleDaysDialog.html
- ui/app/styles/ot/_ot.scss
- ui/test/unit/ot/controller/listViewController.spec.js
- ui/test/unit/ot/controller/otCalendarController.spec.js
- ui/test/unit/ot/controller/surgicalBlockController.spec.js
- ui/test/unit/ot/directives/otCalendarSurgicalAppointment.spec.js
- ui/test/unit/ot/directives/otCalendarSurgicalBlock.spec.js
- ui/test/unit/ot/services/surgicalAppointmentService.spec.js
https://bahmni.atlassian.net/browse/BAH-1170
> Tarun, Gopi | BAH-1170 | MOBN-1628 | Add support to create surgical blocks across days

- README.md
Updated README.md to make it easier for devs to build, contribute, etc.
> BAH-1232: Updated README with build steps and other useful information

- ui/app/common/displaycontrols/bacteriologyresults/directives/bacteriologyResultsControl.js
- ui/test/unit/common/displaycontrols/bacteriologyResults/directives/bacteriologyResultsControl.spec.js
* Bindu | MOBN-446 | Change bacteriology save call from specimen to bahmniEncounter api
* Bindu | MOBN-446 | Add browser close dialog message
Product JIRA link -> https://bahmni.atlassian.net/browse/BAH-1220
> Bindu | BAH-1220 | Change bacteriology save call from specimen to bahmniEncounter API

- ui/app/i18n/ot/locale_en.json
- ui/app/ot/controller/calendarViewController.js
- ui/app/ot/controller/listViewController.js
- ui/app/ot/controller/otCalendarController.js
- ui/app/ot/controller/surgicalBlockController.js
- ui/app/ot/directives/otCalendarSurgicalAppointment.js
- ui/app/ot/directives/otCalendarSurgicalBlock.js
- ui/app/ot/services/surgicalAppointmentService.js
- ui/app/ot/views/addActualTimeDialog.html
- ui/app/ot/views/calendarSurgicalBlock.html
- ui/app/ot/views/otCalendar.html
- ui/app/ot/views/otWeeklyCalendar.html
- ui/app/ot/views/surgicalAppointmentDialog.html
- ui/app/ot/views/surgicalBlockDialog.html
- ui/app/ot/views/surgicalBlockMultipleDaysDialog.html
- ui/app/styles/ot/_ot.scss
- ui/test/unit/ot/controller/listViewController.spec.js
- ui/test/unit/ot/controller/otCalendarController.spec.js
- ui/test/unit/ot/controller/surgicalBlockController.spec.js
- ui/test/unit/ot/directives/otCalendarSurgicalAppointment.spec.js
- ui/test/unit/ot/directives/otCalendarSurgicalBlock.spec.js
- ui/test/unit/ot/services/surgicalAppointmentService.spec.js
* Tarun | MOBN-1628 | Add confirmation popup for creating surgical block across multiple days
* Tarun | MOBN-1628 | Fix day view to show surgical blocks created across days
* Gopi ,Tarun | MOBN-1628 | Removed Syntax Error Which Is Causing Error PopUp on OT Page Load
* Tarun, Gopi | MOBN-1628 | Fix week view to show surgical blocks created across days
* Tarun, Gopi | MOBN-1628 | Fix list view to show surgical appointments created across days
* Gopi,Tarun | MOBN-1628 | Fixed Existing UI Tests
* Tarun, Gopi | MOBN-1628 | Show both startdate and enddate in surgical block dialog if both dates are different
* Gopi,Tarun | MOBN-1628 | Fixed Remaining UI Tests
* Tarun, Gopi | MOBN-1628 | Add date input field in actual time dialog
* Tarun, Gopi | MOBN-1628 | Add date in est & actual time fields in …
> Tarun, Gopi | BAH-1170 | Add support to create surgical blocks across days

- ui/app/bedmanagement/controllers/adtController.js
- ui/test/unit/bedmanagement/controllers/adtController.spec.js
* Tarun, Venky | MOBN-1430 | Fix issues related to multiple clicks while admitting, transferring and discharging
* Tarun,Venky | MOBN-1430 | Fix unit cases
Bahmni JIRA Card - https://bahmni.atlassian.net/browse/BAH-1189
> Tarun, Venky | BAH-1189 | Fix issues related to multiple clicks while admitting, transferring and discharging 

- ui/app/common/patient/services/patientService.js
Co-authored-by: SanoferSameera <sanofersameera25@gmail.com>
> BAH-1687, BAH-1688 | Fix. Unable to search the patient using name and % in All search tab

- README.md
- package/docker/httpd.conf
- package/docker/index.html
Co-authored-by: stavtnameh <hemanth.v@beehyv.com>
> BAH-1816 | Disabling search engine crawling/indexing

- ui/app/clinical/displaycontrols/patientContext/views/patientContext.html
Co-authored-by: deepthi-m <deepthi.mantena@thoughtworks.com>
> BAH-1946 | Switch the position of ui element

- ui/app/registration/controllers/patientCommonController.js
- ui/test/unit/registration/controllers/patientCommonController.spec.js
Co-authored-by: SanoferSameera <sanofersameera25@gmail.com>
> BAH-1953 | fixed. updated primaryContact to phoneNumber

- ui/app/registration/controllers/editPatientController.js
Co-authored-by: Kavitha S <kavitha.s@thoughtworks.com>
> BAH-1768 | Updated the message reference to a constant file.

- ui/app/i18n/registration/locale_en.json
- ui/app/registration/constants.js
- ui/app/registration/controllers/visitController.js
- ui/app/registration/views/visit.html
Co-authored-by: deepthi-m <deepthi.mantena@thoughtworks.com>
> BAH-1808 | added navigation to patient dashboard from registration

- ui/app/registration/controllers/editPatientController.js
Co-authored-by: Kavitha S <kavitha.s@thoughtworks.com>
> BAH-1768 | Encoded the whatsapp message to display special characters

- ui/app/common/photo-capture/directives/capturePhoto.js
Co-authored-by: Soorya Kumaran C <sooryakumaran.c@thoughtworks.com>
> BAH-2229 | removed file name and canvas if error exists

- ui/app/common/displaycontrols/observation/directives/bahmniObservation.js
- ui/app/common/displaycontrols/observation/helpers/groupingFunctions.js
- ui/app/common/displaycontrols/observation/views/observationDisplayControl.html
- ui/app/common/domain/services/visitDocumentService.js
- ui/app/common/obs/directives/showObservation.js
- ui/app/common/obs/views/showObservation.html
- ui/app/styles/clinical/_orders.scss
- ui/app/styles/clinical/_patientDashboard.scss
patient-documents-display-control-ui-fixes-in-dashboard
> BAH-1995 | patient-documents-display-control-ui-fixes-in-dashboard

- ui/yarn.lock
JIRA - [https://bahmni.atlassian.net/browse/BAH-2297](https://bahmni.atlassian.net/browse/BAH-2297)
> BAH-2297 | updating Bahmni ui form-controls and other dependencies

- ui/app/common/patient-search/controllers/patientsListController.js
- ui/app/common/patient-search/models/search.js
- ui/app/common/patient-search/views/patientsList.html
- ui/app/common/patient/services/patientService.js
- ui/app/registration/controllers/searchPatientController.js
- ui/test/unit/registration/controllers/searchPatientController.spec.js
BAH-1720|configure-the-patient-queues-active-and-all-to-search-the-patients by ABHA id
> BAH-1720|configure-the-patient-queues-active-and-all-to-search-the-patients

- ui/app/clinical/index.html
- ui/app/common/constants.js
- ui/app/common/domain/services/diagnosisService.js
JIRA - [https://bahmni.atlassian.net/browse/BAH-2358](https://bahmni.atlassian.net/browse/BAH-2358)
> BAH-2358 | Making emrapi Diagnosis limit as configuaration

- ui/app/common/obs/models/observation.js
- ui/app/common/obs/views/showObservation.html
- ui/test/unit/common/obs/observation.spec.js
- Resolving issue to display Form2 forms on patient dashboard
Note: Tested these changes with Form 1 and Form 2 forms
> BAH-2285 - [ Bindu, Rohit ] - Resolves issue to display Form2 forms on patient dashboard

- ui/app/common/displaycontrols/observation/directives/bahmniObservation.js
- ui/app/common/displaycontrols/observation/services/formRecordTreeBuildService.js
- ui/app/common/obs/views/showObservation.html
- ui/app/styles/clinical/_patientDashboard.scss
- ui/app/styles/clinical/_visit.scss
- ui/test/unit/common/displaycontrols/observation/services/formRecordTreeBuildService.spec.js
- Fixes displaying group values in display controls
> BAH-2285 - [ Rohit ] - Fixes displaying group values in display controls

- package/docker/index.html
Jira link: https://bahmni.atlassian.net/browse/BAH-2284?atlOrigin=eyJpIjoiOGVjNmJjMjM5OWJlNDNiNDg4MjU5ZjBhNzY2NDBkMjQiLCJwIjoiaiJ9
Screenshot of Landing page:
> BAH-2284 | Refactor. Landing page to display apps based on configuration

- ui/app/clinical/common/views/patientInfoPrint.html
- ui/app/clinical/common/views/visitHeader.html
- ui/app/clinical/common/views/visitSummary.html
- ui/app/clinical/common/views/visitTabPrint.html
- ui/app/clinical/config/visitMandatoryTab.json
- ui/app/clinical/displaycontrols/investigationresults/views/investigationChart.html
- ui/app/clinical/displaycontrols/treatmentData/views/treatmentTableRow.html
- ui/app/common/displaycontrols/diagnosis/views/diagnosisDisplayControl.html
- ui/app/common/obs/views/showObservation.html
- ui/app/common/patient/filters/age.js
- ui/app/i18n/adt/locale_en.json
- ui/app/i18n/adt/locale_es.json
- ui/app/i18n/adt/locale_fr.json
- ui/app/i18n/adt/locale_pt_BR.json
- ui/app/i18n/clinical/locale_en.json
- ui/app/i18n/clinical/locale_es.json
- ui/app/i18n/clinical/locale_fr.json
- ui/app/i18n/clinical/locale_pt_BR.json
- ui/app/i18n/ipd/locale_en.json
- ui/app/styles/clinical/_patientDashboard.scss
- ui/app/styles/clinical/_program.scss
- ui/app/styles/print.scss
- ui/test/unit/common/patient/filters/dateToAge.spec.js
- Configuring the template for printing the visit details from the patient dashboard
- Jira: https://bahmni.atlassian.net/browse/BAH-2185
> BAH-2185-feature - [ Rohit ] - Configure the template for printing the visit details from the patient dashboard

- ui/app/common/ui-helper/directives/conceptAutocomplete.js
- Adding partial and reverse order word search for form-1 forms
- Jira: https://bahmni.atlassian.net/browse/BAH-2421
> BAH-2421 - [ Rohit ] - Adds reverse order words and partial search for form-1 forms

- ui/app/clinical/common/views/visitSummary.html
- ui/app/clinical/config/visitMandatoryTab.json
- ui/app/common/displaycontrols/diagnosis/views/diagnosisDisplayControl.html
- ui/app/common/obs/views/showObservation.html
This PR is about - 
- Resolving concept display issues
> BAH-2185 - [ Rohit ] - Resolves concept display issues

- ui/app/common/patient/mappers/patientMapper.js
Co-authored-by: manimaarans <manimaaran@beehyv.com>
> BAH-2534 | Updated to include postalCode in the patientMapper

- ui/app/clinical/index.html
- ui/app/common/patient-search/directives/scrollableTabs.js
- ui/app/common/patient-search/views/patientsList.html
- ui/app/common/util/swipeUtil.js
- ui/app/styles/clinical/_clinicalIndex.scss
- ui/app/styles/clinical/_patientSearch.scss
- ui/app/styles/clinical/_scrollable-tabs.scss
> [BAH-2527] Add responsive behaviour to tabs

- ui/app/styles/adt/_adt.scss
- ui/app/styles/bahmni-components/_ngDialog.scss
> [BAH-2547] Styling fix for modal to be responsive

- ui/app/common/auth/authentication.js
- ui/test/unit/common/auth/authentication.spec.js
- Resolving not able to login issue, as login is asking for OTP
- Jira: https://bahmni.atlassian.net/browse/BAH-2573
> BAH-2573 - [ Rohit ] - Resolves not able to login issue

- ui/app/styles/bahmni-components/_templateController.scss
- ui/app/styles/clinical/_observations.scss
| **Before**                                                                                                                                | **After**                                                                                                                                 |
| <img width="395" alt="image" src="https://user-images.githubusercontent.com/97936617/203271671-36a61cd5-f251-4a37-bdcb-40e675422fa0.png"> | <img width="387" alt="image" src="https://user-images.githubusercontent.com/97936617/203271542 …
> [BAH-2609] Fix Add observations form

- ui/app/clinical/common/controllers/visitHeaderController.js
- ui/app/clinical/common/views/mobileHeader.html
- ui/app/clinical/common/views/visitHeader.html
- ui/app/clinical/consultation/controllers/consultationController.js
- ui/app/clinical/dashboard/controllers/patientDashboardController.js
- ui/app/clinical/dashboard/directives/recentPatients.js
- ui/app/clinical/dashboard/views/clinicalDashboardHeader.html
- ui/app/clinical/dashboard/views/dashboard.html
- ui/app/clinical/dashboard/views/recentPatients.html
- ui/app/clinical/displaycontrols/patientContext/views/patientContext.html
- ui/app/clinical/index.html
- ui/app/common/patient/filters/birthDateToAgeText.js
- ui/app/common/ui-helper/directives/historyBack.js
- ui/app/i18n/clinical/locale_en.json
- ui/app/i18n/clinical/locale_es.json
- ui/app/i18n/clinical/locale_fr.json
- ui/app/i18n/clinical/locale_pt_BR.json
- ui/app/styles/bahmni-components/_gallery.scss
- ui/app/styles/bahmni-layout/_layout.scss
- ui/app/styles/clinical.scss
- ui/app/styles/clinical/_clinicalIndex.scss
- ui/app/styles/clinical/_patientDashboard.scss
- ui/app/styles/clinical/_visit.scss
- ui/app/styles/common/_mobileHeader.scss
- ui/test/unit/clinical/common/controllers/visitHeaderController.spec.js
- ui/test/unit/clinical/controllers/consultationController.spec.js
- ui/test/unit/clinical/controllers/patientDashboardController.spec.js
- ui/test/unit/clinical/directives/recentPatients.spec.js
- ui/test/unit/clinical/patientcontrolpanel/directives/patientControlPanel.spec.js
|   |  Before  |  After |
|----|---|---|
|  Dashboard |  <img width="373" alt="Screenshot 2022-11-21 at 1 10 15 PM" src="https://user-images.githubusercontent.com/97936617/202993080-6cfd62cb-f2d5-4726-b131-a6a7414be4a4.png">  |  <img width="377" alt="Screenshot 2022-11-21 at 12 55 34 PM" src="https://user-images.githubusercontent.com/97936617/202993087-909d6376-e7e6-4b71-8e61-24969260cec0.png"> |
|  Consultation | <img width="377" alt="Screenshot 2022-11-21 at 1 10 25 PM" src="https://user-images.githubusercontent.com/97936617/202993082-288e2a7a-6827-42de-9394-c2438529035a.png">   |  <img width="373" alt="Screenshot 2022-11-21 at 12 56 13 PM" src="https://user-images.githubusercontent.com/97936617/202993091-40dc5216-2c5c-4627-91bd-09733e076e69.png">|
> [BAH-2546] Header responsive

- ui/app/clinical/common/views/mobileHeader.html
- ui/app/clinical/consultation/views/treatment.html
- ui/app/clinical/consultation/views/treatmentSections/drugOrderHistory.html
- ui/app/styles/bahmni-components/_inPageTabs.scss
- ui/app/styles/clinical/_consultation.scss
- ui/app/styles/clinical/treatment/_treatment.scss
- ui/app/styles/common/_mobileHeader.scss
| **Before**                                                                                                                                | **After**                                                                                                                                 |
| <img width="332" alt="image" src="https://user-images.githubusercontent.com/97936617/204277346-81f1c898-b5ec-4fb7-97bc-d5afac7e5975.png"> | <img width="331" alt="image" src="https://user-images.githubusercontent.com/97936617/204277195 …
> [BAH-2611] Fixes to medication tab

- ui/app/clinical/displaycontrols/investigationresults/directives/investigationTableRow.js
JIRA Bug - https://bahmni.atlassian.net/browse/BAH-2306?focusedCommentId=16671
The symbol greater than is added before the Minimum Normal Value.
> Fixed the Range for Minimum Normal

- ui/app/clinical/consultation/controllers/clinicalController.js
- ui/app/clinical/consultation/controllers/orderController.js
- ui/app/clinical/consultation/views/orderTemplateViews/ordersTemplate.html
- ui/app/clinical/consultation/views/orders.html
- ui/app/common/concept-set/directives/conceptSetGroup.js
- ui/app/styles/bahmni-components/_inPageTabs.scss
- ui/app/styles/clinical/_draggableDiv.scss
- ui/app/styles/clinical/_observations.scss
- ui/app/styles/clinical/_orders.scss
- ui/app/styles/clinical/treatment/_treatment.scss
- ui/app/styles/common/_mobileHeader.scss
**Before**
**After**
| Collapsed                                                                                                                                 | Expanded                                                                                                                                  |
| <img width="370" alt="image" src="https://user-images.githubusercontent.com/97936617/205043626-abef3047-3182-43e7-a456-b607fbda696c.png"> | <img width="362" alt="image" …
> [BAH-2612] Order tab Mobile fixes

- ui/app/clinical/consultation/views/orderTemplateViews/ordersTemplate.html
- ui/app/styles/bahmni-components/_buttons.scss
- ui/app/styles/bahmni-components/_templateController.scss
- ui/app/styles/clinical/_observations.scss
- ui/app/styles/clinical/treatment/_treatment.scss
> [BAH-2492] Change Add observation button color

- ui/app/styles/clinical/_patientSearch.scss
> [BAH-2544] Better cards for active patients

- ui/app/clinical/consultation/views/conditionRow.html
- ui/app/clinical/consultation/views/conditions.html
- ui/app/clinical/consultation/views/diagnosis.html
- ui/app/clinical/consultation/views/diagnosisRow.html
- ui/app/styles/clinical/_diagnosis.scss
| **Before**                                                                                                                                | **After**                                                                                                                                 |
| <img width="326" alt="image" src="https://user-images.githubusercontent.com/97936617/206634138-cc5a0a1e-e317-4953-b4f0-331ac5f2e5c2.png"> | <img width="353" alt="image" src="https://user-images.githubusercontent.com/97936617/206634820 …
> [BAH-2610] Diagnosis Tab responsive changes

- ui/app/clinical/consultation/views/conditionRow.html
- ui/app/clinical/consultation/views/consultation.html
- ui/app/styles/bahmni-components/_inPageTabs.scss
- ui/app/styles/clinical/_consultation.scss
- ui/app/styles/clinical/_diagnosis.scss
- ui/app/styles/clinical/treatment/_treatment.scss
| **Before**                                                                                                                                                              | **After**                                                                                                                                                               |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <img width="364" alt="Screenshot 2022-12-12 at 4 34 50 PM" …
> [BAH-2676] Consultation tab responsive fixes

- ui/app/clinical/consultation/controllers/consultationController.js
- ui/app/styles/bahmni-components/_gallery.scss
- ui/test/unit/clinical/controllers/consultationController.spec.js
Bugfix -- Browser Back button highlighting multiple tabs in consultation
> [BAH-2636] Back button tab highlight 

- .github/workflows/build_publish.yml
- .github/workflows/validate_pr.yml
…age tags
Co-authored-by: Siva Reddy <sivareddy.pathuri@thoughtworks.com>
JIRA https://bahmni.atlassian.net/browse/BS-39
Published Images Screenshot
> BS-39 | Siva,Vijay | Publish openmrs-module-bahmniapps with SNOMED images

- ui/app/registration/controllers/navigationController.js
- ui/app/registration/views/editpatient.html
- ui/app/registration/views/header.html
- ui/app/registration/views/newpatient.html
- ui/app/styles/common/_bahmniGlobal.scss
- ui/app/styles/registration/_patientCommonInformation.scss
- ui/app/styles/registration/_patientPhoto.scss
- ui/app/styles/registration/_registration.scss
- ui/app/styles/registration/_registrationHeader.scss
- ui/app/styles/registration/_relationship.scss
> [BAH-2757] Registration module responsive changes

- ui/app/common/photo-capture/directives/capturePhoto.js
- ui/app/common/photo-capture/views/photo.html
- ui/app/registration/views/visit.html
- ui/app/styles/registration/_patientCommonInformation.scss
- ui/app/styles/registration/_patientPhoto.scss
- ui/app/styles/registration/_registration.scss
| **Before**                                                                                                                                | **After**                                                                                                                                 |
| <img width="361" alt="image" src="https://user-images.githubusercontent.com/97936617/211517426-2dcff43d-dd88-49d5-8427-d060cfe8e3e7.png"> | <img width="353" alt="image" src="https://user-images.githubusercontent.com/97936617/211519302 …
> Registration module responsiveness fixes | Part 2

- ui/app/clinical/consultation/controllers/diagnosisController.js
- ui/app/clinical/consultation/mappers/encounterTransactionMapper.js
- ui/test/unit/clinical/consultation/controllers/diagnosisController.spec.js
Jira - https://bahmni.atlassian.net/browse/BS-75
Update Payload while saving diagnosis:
- Coded Answer UUID is prefixed with conceptSystem and followed by */*
- Prefix Coded Answer UUID with conceptSystem when available.
> BS-75 | UI changes for Diagnosis Save

- ui/app/clinical/common/models/drugOrderViewModel.js
- ui/app/clinical/consultation/views/treatmentSections/drugOrderHistory.html
- ui/app/styles/clinical/treatment/_treatment.scss
- ui/app/styles/registration/_registration.scss
> BAH-2868 Medication Prescriptions UI improvement

- ui/app/clinical/consultation/views/newDrugOrders.html
- ui/app/clinical/consultation/views/treatmentSections/drugOrderHistory.html
- ui/app/styles/clinical/treatment/_treatment.scss
> [BAH-2868] Medication improvements for new prescription

- .github/workflows/build_publish.yml
JIRA https://bahmni.atlassian.net/browse/BS-42
> Siva Reddy | BS-42 | Auto deployment to SNOMED Dev Environment

- ui/app/common/ui-helper/services/messagingService.js
Jira - https://bahmni.atlassian.net/browse/BS-48
- When the connectivity to the SNOMED CT server is not available, display a toast message to the user. “The terminology server is unavailable right now. Please try again later.”
- Fixed error timeout issue
> Bs 48 | Diagnosis Search Availability

- ui/app/clinical/consultation/controllers/diagnosisController.js
- ui/app/common/domain/services/diagnosisService.js
- ui/app/common/ui-helper/services/messagingService.js
- ui/app/i18n/clinical/locale_en.json
- ui/app/i18n/clinical/locale_es.json
- ui/app/i18n/clinical/locale_fr.json
- ui/app/i18n/clinical/locale_pt_BR.json
Jira - https://bahmni.atlassian.net/browse/BS-48
Add a generic error message "Something unexpected happened. Please contact administrator." to be displayed whenever an error occurs within the terminology server.
> BS-48 | Diagnosis Search Availability

- ui/app/clinical/displaycontrols/investigationresults/views/investigationTableRow.html
- ui/app/clinical/displaycontrols/treatmentData/directives/treatmentData.js
This PR fixes the issues addressed as part of [BAH-2898](https://bahmni.atlassian.net/browse/BAH-2898) and [BAH-2901](https://bahmni.atlassian.net/browse/BAH-2901) on the release-0.93 version
- Fixes a typo in treatment data display control
- Fix for test name not shown in lab result display control when result is associated with a file.
> Fixes for BAH-2898 & BAH-2901

- ui/app/clinical/consultation/views/treatmentSections/addTreatment.html
Include a translate filter in the CDSS critical alert select input options to enable key translation.
Bug
Fixed
https://bahmni.atlassian.net/browse/BS-101
> BS-101 | Patrick | Add translate filter to CDSS critical alert options

- ui/app/common/attributeTypes/views/attributeInformation.html
- ui/app/registration/initialization.js
Added registration location on registration page
JIRA link -> [https://bahmni.atlassian.net/browse/BAH-3018](https://bahmni.atlassian.net/browse/BAH-3018)
> Ritesh| BAH-3018 | Registration location

- ui/app/common/patient-search/constants.js
- ui/app/common/patient-search/controllers/patientsListController.js
- ui/app/common/patient-search/views/patientsList.html
- ui/app/styles/clinical/_patientSearch.scss
- ui/test/unit/common/patient-search/controllers/patientsListController.spec.js
Asana link -> https://app.asana.com/0/1204322126657135/1204551237996195
This PR has changes 
- To bring in sort buttons for patient list in tabular view in the clinical module. 
- To add Patient ID as identifier header (CURE - specific)
> Arjun | 1204551237996195 | Configuration of columns in clinical list view 

- ui/app/adt/models/wardDetails.js
- ui/app/adt/views/wardList.html
- ui/app/i18n/adt/locale_en.json
- ui/app/styles/adt/_adt.scss
JIRA card -> [https://bahmni.atlassian.net/browse/BAH-3025](https://bahmni.atlassian.net/browse/BAH-3025)
As part of this PR,
- Added a search button for IPD ward list for each ward
- Enabled translation for the headers in the ward list table view
- Enabled removing/adding the fields to the table through sql file. Earlier these fields have hardcode in the code to add/remove a column in the table.
> Bindu | BAH-3025 | Ability to view the Ward Nurse Dashboard page with its elements and Search by Patient Name or ID

- ui/app/clinical/consultation/controllers/diagnosisController.js
- ui/app/i18n/clinical/locale_en.json
Removed custom TS server error message 
https://bahmni.atlassian.net/browse/BS-48
> Removed custom TS server error message

- README.md
Add wiki link in readme
**Jira**
https://bahmni.atlassian.net/browse/BS-113
> Add wiki link in readme

- ui/app/adt/models/wardDetails.js
- ui/app/styles/adt/_adt.scss
JIRA card -> [https://bahmni.atlassian.net/browse/BAH-3025](https://bahmni.atlassian.net/browse/BAH-3025)
As part of this card,
- added "Ward" fields in the wardlist
> Bindu | BAH-3025 | Handle showcase feedback

- ui/package.json
- ui/yarn.lock
JIRA - https://bahmni.atlassian.net/browse/BS-108
> BS-108 | Bahmni Form Controls version upgrade to 0.93.11-snomed.1

- package/docker/Dockerfile
- ui/app/i18n/registration/locale_en.json
- ui/app/registration/constants.js
- ui/app/registration/directives/patientRelationship.js
- ui/app/registration/views/patientRelationships.html
- ui/app/styles/registration/_relationship.scss
[JIRA link](https://bahmni.atlassian.net/browse/BAH-3034?atlOrigin=eyJpIjoiMjYzYjVhYmJhZjAzNDY5ZmExZTBlMWRlY2NmMjQ2MmEiLCJwIjoiaiJ9)
[Asana link](https://app.asana.com/0/1204322126657135/1204637030393153)
This PR has the following changes ->
- `Add Person` button for each relationship which when clicked would render the iframe to show the [person-management-app](https://github.com/Bahmni/person-management-app).
-  iframe to view the [person-management-app](https://github.com/Bahmni/person-management-app).
- Modify the relationship field once a person is added through the iframe
- Update Dockerfile to package [person-management-app](https://github.com/Bahmni/person-management-app) with bahmniapps
> Arjun | BAH-3034 | Capture relationship/contacts in patient registration

- ui/app/ot/controller/calendarViewController.js
- ui/app/ot/controller/otCalendarController.js
- ui/app/ot/views/home.html
- ui/app/ot/views/otCalendar.html
- ui/app/styles/ot/_ot.scss
- ui/app/styles/ot/_otCalendar.scss
- ui/test/unit/ot/controller/otCalendarController.spec.js
Adds a toggle to switch between location based OT view and provider based OT view.
Fixes date picker buttons
Jira ref : [BAH-3050](https://bahmni.atlassian.net/browse/BAH-3050)
Sample Screenshot :
> BAH-3050 | add provider based OT view and date picker

- package/docker/Dockerfile
The PR has fix to pull latest build from [person-management-app](https://github.com/Bahmni/person-management-app) and bundle it with bahmniapps
> [Arjun] | fix. Dockerfile for building bahmniapps image with person-management app

- ui/app/styles/bahmni-components/_navigation.scss
- ui/app/styles/bahmni-components/_splitButton.scss
- ui/app/styles/bahmni-helper/_base.scss
- ui/app/styles/clinical/_patientSearch.scss
- ui/app/styles/document-upload/_upload.scss
- ui/app/styles/home/_home.scss
- ui/app/styles/registration/_registration.scss
- ui/app/styles/registration/_registrationHeader.scss
- ui/app/styles/registration/_registrationSearch.scss
- ui/package.json
This PR fixes the issue of border getting cropped for various input boxes
[Screenshots of the issues](https://docs.google.com/document/d/1kSFIz5-V0XDTSeVamDGxRb1zIdx3o7OsioDfsAZfz-I/edit)
> Phani | A- 1204419984112147 | Fix css for Blue border in search boxes on focus

- ui/app/common/ui-helper/controllers/messageController.js
- ui/test/unit/common/ui-helper/controllers/messageController.spec.js
Reverts Bahmni/openmrs-module-bahmniapps#594
> Revert "Parvathy | BAH-2805 | Fix. Copy Error Button"

- README.md
For docker development, and link to Github actions, etc.
> [Gurpreet] Updated README.md with latest instructions

- ui/app/common/patient/services/patientService.js
- ui/test/unit/common/patient/services/patientService.spec.js
Sends additional search param to be filtered out from lucene search based on config
Jira ref : [BAH-3065](https://bahmni.atlassian.net/browse/BAH-3065)
> BAH-3065 | Additional search param for lucene search

- ui/app/common/ui-helper/controllers/messageController.js
- ui/test/unit/common/ui-helper/controllers/messageController.spec.js
Jira card -> https://bahmni.atlassian.net/browse/BAH-2805
The issue with the copy error button in the error popup has been resolved in this PR. Previously, the button was copying the translate key instead of the error message (translate value). This PR includes the necessary fixes to ensure that the error message is correctly copied when the button is clicked.
> BAH-2805 | Parvathy | Fix. Copy error button

- ui/app/adt/controllers/wardListController.js
- ui/app/common/patient/services/patientService.js
Fixes eslint errors from the previous merges
> Fix | fixed eslint errors

- ui/app/common/ui-helper/header.html
- ui/app/orders/controllers/orderFulfillmentController.js
- ui/app/orders/views/orderFulfillment.html
- ui/app/styles/bahmni-layout/_layout.scss
- ui/app/styles/clinical/_orders.scss
- ui/app/styles/common/_bahmniGlobal.scss
This PR:
- Fixes the alignment of additional header elements rendered in Orders module
- Adds a new function to display the concept, passed from config , as a lebel on each order
[Detailed Documentation](https://bahmni.atlassian.net/wiki/spaces/BAH/pages/3199729728/Configurable+Orders+Label)
> Umair | BAH-3070 | Ability to take ownership of radiology orders

- ui/app/adt/controllers/wardListController.js
- ui/app/adt/models/wardDetails.js
- ui/app/adt/views/wardList.html
- ui/app/clinical/displaycontrols/patientContext/directives/patientContext.js
- ui/app/clinical/displaycontrols/patientContext/views/patientContext.html
- ui/app/common/displaycontrols/patientprofile/views/patientProfile.html
- ui/app/common/patient-search/controllers/patientsListController.js
- ui/app/common/patient-search/models/search.js
- ui/app/common/patient-search/views/patientsList.html
- ui/app/common/patient/services/patientService.js
- ui/app/styles/clinical/_patientDashboard.scss
- ui/app/styles/clinical/_patientSearch.scss
- ui/app/styles/clinical/_visit.scss
This PR
1. modifies patient search api to return custom person attribute
2. adds kid icon to patient dashboard , clinical and program queues, ward list  etc alongside patient details based on custom person attribute value returned 
JIRA Reference:[ Add kid icon]( https://bahmni.atlassian.net/jira/software/c/projects/BAH/boards/55?modal=detail&selectedIssue=BAH-3078 )
> Phani, Sowmya | BAH-3078 | Configures custom person attribute and adds kid icon

- ui/test/unit/clinical/controllers/addTreatmentController.spec.js
Asana link - https://app.asana.com/0/1204322126657135/1204551237996191/f
Jira Link - https://bahmni.atlassian.net/browse/BAH-3056
> Soorya | BAH-3056 | Fix test issues caused while adding rule based calculation 

- ui/app/registration/directives/patientRelationship.js
JIRA link - https://bahmni.atlassian.net/browse/BAH-3057?atlOrigin=eyJpIjoiN2QzNWI3MjdmZmI1NDY2Yzg2MDQ4ZDdlMDIxZjE2MGMiLCJwIjoiaiJ9
This PR has changes to fix the bug of replacing previous relationships when a new relationship is added in the patient relationship section.
> Arjun | BAH-3057 | Adding more than one relationship for a patient replaces all the previous relationships 

- ui/app/ot/controller/listViewController.js
- ui/app/ot/mappers/SurgicalBlockMapper.js
- ui/app/ot/services/surgicalAppointmentService.js
- ui/app/ot/views/listView.html
- ui/app/styles/ot/_ot.scss
- ui/test/unit/ot/controller/listViewController.spec.js
- ui/test/unit/ot/services/surgicalAppointmentService.spec.js
Shows names of all primary diagnoses in OT list view separated by commas
JIRA ref [BAH-3092](https://bahmni.atlassian.net/browse/BAH-3092)
Sample screenshot:
> BAH-3092 | Show primary diagnoses in OT list view

- ui/app/clinical/displaycontrols/treatmentData/views/treatmentTableRow.html
- ui/app/styles/clinical/_patientDashboard.scss
JIRA - https://bahmni.atlassian.net/jira/software/c/projects/BAH/boards/55?modal=detail&selectedIssue=BAH-3079
This PR has changes to modify the view of treatments display control in the patient dashboard.
> BAH-3079 | Incorporate CSS changes for treatments display control

- ui/package.json
- ui/yarn.lock
Bumps up form-controls version to 0.93.12
> BAH-3109 | Bump up form controls version

- micro-frontends/package.json
- micro-frontends/yarn.lock
- ui/app/clinical/dashboard/controllers/patientDashboardController.js
- ui/app/clinical/dashboard/views/dashboard.html
- ui/app/i18n/clinical/locale_en.json
Link to JIRA card -
https://bahmni.atlassian.net/browse/BAH-3113
> Sowmya|Phani | BAH-3113 : Adds React components for the right panel of Drug Chart(MAR)

- ui/app/common/attributeTypes/directives/attributeTypes.js
Asana Link: https://app.asana.com/0/1204322126657135/1204719912797190/f
> Add a condition to handle location name error in registration page

- micro-frontends/src/ipd/index.js
- ui/app/clinical/dashboard/controllers/patientDashboardController.js
- ui/app/clinical/dashboard/views/dashboard.html
- ui/app/clinical/displaycontrols/treatmentData/directives/treatmentTableRow.js
- ui/app/clinical/displaycontrols/treatmentData/views/treatmentTableRow.html
- ui/test/unit/clinical/controllers/patientDashboardController.spec.js
Asana - https://app.asana.com/0/1204322126657135/1205221989222721
This PR has changes to refactor angular wrappers that are used in bahmniapps to communicate with IPD frontend code.
> Arjun | A-1205221989222721 | Angular wrappers refactor

- ui/app/clinical/consultation/controllers/addTreatmentController.js
Jira - https://bahmni.atlassian.net/browse/BS-160
Added a fix for closing the alert when the drug is removed/cleared
> BS-160 | Patrick | Close alerts when medication input is cleared

- ui/app/clinical/consultation/controllers/drugOrderHistoryController.js
Story ref: [BAH-3140](https://bahmni.atlassian.net/browse/BAH-3140)
> BAH-3140 | Fix to handle null visit in print medication

- ui/app/ot/services/surgicalAppointmentService.js
- ui/test/unit/ot/services/surgicalAppointmentService.spec.js
search for diagnosis information only if the config is present
Story ref: [BAH-3092](https://bahmni.atlassian.net/browse/BAH-3092)
> BAH-3092 | added configurable param for primary diagnosis in OT module

- ui/app/clinical/common/services/treatmentService.js
- ui/app/clinical/consultation/controllers/addTreatmentController.js
- ui/app/clinical/consultation/controllers/drugOrderHistoryController.js
- ui/app/clinical/consultation/directives/newDrugOrders.js
- ui/app/clinical/consultation/views/newDrugOrders.html
- ui/app/clinical/consultation/views/treatmentSections/drugOrderHistory.html
- ui/app/clinical/displaycontrols/treatmentData/directives/treatmentData.js
- ui/app/clinical/displaycontrols/treatmentData/views/treatmentTableRow.html
- ui/app/common/constants.js
- ui/test/unit/clinical/controllers/drugOrderHistoryController.spec.js
JIRA - https://bahmni.atlassian.net/jira/software/c/projects/BAH/boards/55?modal=detail&selectedIssue=BAH-3157
Asana - https://app.asana.com/0/1204322126657135/1204950368410826
This PR has changes to update an IPD to non-IPD medication or vice-versa within the encounter time or if schedules for that order are not created.
> Arjun | BAH-3157 | Ability to switch IPD to non-IPD medication

- ui/app/clinical/dashboard/views/dashboard.html
Cure Bug| https://app.asana.com/0/1204322126657135/1205322391814027/f
> fix. switch to consultation page in drug chart tab

- ui/app/reports/services/reportService.js
**Description**
Jira Ticket: https://bahmni.atlassian.net/jira/software/c/projects/BAH/boards/25?modal=detail&selectedIssue=BAH-3049
> BAH-3049| Samridhi | Rename dateRange key

- ui/app/clinical/consultation/services/exitAlertService.js
- ui/app/common/ui-helper/controllers/messageController.js
- ui/test/unit/clinical/consultation/services/exitAlertService.spec.js
Jira card -> https://bahmni.atlassian.net/browse/BAH-2359
> Parvathy | BAH-2359 | Fix. dependency injection issue

- ui/app/registration/controllers/searchPatientController.js
- ui/app/registration/views/search.html
Documentation: https://bahmni.atlassian.net/wiki/spaces/BAH/pages/3221684257/Patient+Search+by+Phone+Number+in+Registration+Module
[Jira: ](https://bahmni.atlassian.net/browse/BAH-3179)
> BAH-3179 | Config for displaying patient search results

- ui/app/clinical/common/services/treatmentService.js
- ui/app/clinical/consultation/controllers/drugOrderHistoryController.js
- ui/app/clinical/consultation/views/treatmentSections/drugOrderHistory.html
- ui/app/common/domain/services/diagnosisService.js
Asana - https://app.asana.com/0/1204322126657135/1205239860424569
This PR has changes to add dispenser info, ICD-10 codes of prescribed diagnoses based on type passed through config and add observation information (Weight, Height etc) in the prescription printout.
> Arjun | 1205239860424569 | Pre-filling information on prescription printout

- ui/app/i18n/registration/locale_en.json
- ui/app/registration/directives/patientAction.js
[Tanya|Phanindra] | A-1205359902527471 | https://app.asana.com/0/1204322126657135/1205359902527471
> Patient registration redirection

- micro-frontends/src/next-ui/Containers/formDisplayControl/FormDisplayControl.spec.jsx
- micro-frontends/webpack.config.js
> Fix public path

- ui/app/common/displaycontrols/navigationlinks/directives/navigationLinks.js
- ui/app/common/patient-search/controllers/patientsListController.js
- ui/test/unit/common/patient-search/controllers/patientsListController.spec.js
- open links in targeted tabs based on config
JIRA Link : [BAH-3200](https://bahmni.atlassian.net/browse/BAH-3200)
> Abi, Kavitha | A-1205239860424586 | add targeted tab feature for queues

- micro-frontends/README.md
- ui/Gruntfile.js
This PR has changes to add translations added from micro-frontends folder to be made available in the Bahmni ui build
> Arjun | Translations for micro-frontends 

- ui/app/reports/views/reports.html
**Description**
- Fix bug on start date
**Jira Ticket:** https://bahmni.atlassian.net/jira/software/c/projects/BAH/boards/25?modal=detail&selectedIssue=BAH-3049
> BAH-3049 | Samridhi | Put default dates in Report screen to save time

- ui/app/common/displaycontrols/dashboard/views/sections/forms.html
- ui/app/common/displaycontrols/forms/controllers/patientDashboardAllFormsController.js
- ui/app/common/displaycontrols/forms/directives/formsTable.js
- ui/app/common/displaycontrols/forms/views/allForms.html
- ui/app/common/displaycontrols/forms/views/formsTable.html
- ui/app/styles/clinical/_visit.scss
- Based on config, it'll show edit option only for active encounters in the form 1 forms display control
- Shows provider names in the dispaly control
- JIRA Ref: [BAH-3209](https://bahmni.atlassian.net/browse/BAH-3209)
- Screenshots :
> BAH-3209 | Provider name and Control Edit for form display control

- ui/app/common/domain/services/programService.js
- ui/app/common/patient-search/controllers/patientsListController.js
- ui/app/common/uicontrols/programmanagement/controllers/manageProgramController.js
- ui/app/common/uicontrols/programmanagement/views/programEnrollment.html
- ui/app/common/uicontrols/programmanagement/views/programRow.html
- ui/app/styles/clinical/_program.scss
- ui/test/unit/common/uicontrols/programmanagement/controllers/manageProgramController.spec.js
Asana - https://app.asana.com/0/1204322126657135/1205281688916688
This PR has changes to 
- Add redirection from program and initial program state using config
- targetedTab $timeout error fix
> Arjun | A-1205281688916688 | Default values of triage program state

- ui/app/clinical/consultation/services/exitAlertService.js
- ui/app/common/ui-helper/controllers/messageController.js
- ui/test/unit/clinical/consultation/services/exitAlertService.spec.js
JIRA - https://bahmni.atlassian.net/browse/BAH-3182
This PR has changes to fix the dependency issues caused due to changes in the alerts shown in the consultation section. The dependency was being prompted in other locations of Bahmni (eg: home, registration) which was not required. 
Changes made in this PR are brought here - https://github.com/Bahmni/openmrs-module-bahmniapps/pull/677
> BAH-3182 | Dependency injection issue fix

- micro-frontends/src/next-ui/Components/ViewObservationForm/TileItem/TileItem.jsx
- micro-frontends/src/next-ui/Components/ViewObservationForm/TileItem/TileItem.spec.jsx
- micro-frontends/src/next-ui/Components/ViewObservationForm/TileItem/__snapshots__/TileItem.spec.jsx.snap
- micro-frontends/src/next-ui/Components/ViewObservationForm/ViewObservationForm.jsx
- micro-frontends/src/next-ui/Components/ViewObservationForm/ViewObservationForm.spec.jsx
- micro-frontends/src/next-ui/Components/ViewObservationForm/__snapshots__/ViewObservationForm.spec.jsx.snap
- micro-frontends/src/next-ui/Components/ViewObservationForm/viewObservationForm.scss
- micro-frontends/src/next-ui/Containers/formDisplayControl/FormDisplayControl.jsx
- micro-frontends/src/next-ui/Containers/formDisplayControl/FormDisplayControl.spec.jsx
- micro-frontends/src/next-ui/constants.js
- micro-frontends/src/next-ui/utils/FormDisplayControl/BuildFormView.js
- micro-frontends/src/next-ui/utils/FormDisplayControl/FormView.js
- ui/app/common/displaycontrols/dashboard/directives/dashboard.js
- ui/app/common/displaycontrols/dashboard/models/dashboardSection.js
- ui/app/common/displaycontrols/dashboard/views/sections/nextUISection.html
Asana Link: https://app.asana.com/0/1204322126657135/1205283475057417/f
In this PR:
Have added angular to react migration of logic to build the formMap object for the react to render
Included Model for the viewing the form
Fixed the date and datetime format
Created a separate display control for formsV2React
> feat: View Observation Form in React [Ayush | Soorya]

- ui/app/common/patient-search/controllers/patientsListController.js
- ui/app/common/patient-search/views/patientsList.html
- ui/test/unit/common/patient-search/controllers/patientsListController.spec.js
JIRA ref : [BAH-3225](https://bahmni.atlassian.net/browse/BAH-3225)
Existing view:
Sample screenshot after custom filtering and ordering
> BAH-3225 | Custom filtering/ordering of headings in tabular view

- micro-frontends/src/next-ui/Components/ViewObservationForm/TileItem/TileItem.jsx
- micro-frontends/src/next-ui/Components/ViewObservationForm/TileItem/TileItem.spec.jsx
- micro-frontends/src/next-ui/Components/ViewObservationForm/TileItem/__snapshots__/TileItem.spec.jsx.snap
- micro-frontends/src/next-ui/Components/ViewObservationForm/ViewObservationForm.jsx
- micro-frontends/src/next-ui/Components/ViewObservationForm/ViewObservationForm.spec.jsx
- micro-frontends/src/next-ui/Components/ViewObservationForm/__snapshots__/ViewObservationForm.spec.jsx.snap
- micro-frontends/src/next-ui/Components/ViewObservationForm/viewObservationForm.scss
- micro-frontends/src/next-ui/Containers/formDisplayControl/FormDisplayControl.jsx
- micro-frontends/src/next-ui/Containers/formDisplayControl/FormDisplayControl.spec.jsx
- micro-frontends/src/next-ui/Containers/formDisplayControl/formDisplayControl.scss
- micro-frontends/src/next-ui/utils/FormDisplayControl/FormView.js
- micro-frontends/src/styles/carbon-theme.scss
→ Showing notes
→ Spinner while loading the form
→ Complex data type (example surgeons, Operation room) 
→ Fixing Header
→ UI feedback to align date time in display control
> View Observation Forms with complex data type

- ui/app/reports/controllers/reportsController.js
- ui/app/reports/services/reportService.js
- ui/test/unit/reports/controllers/reportsController.spec.js
**Description**
- Updated controller with previous month start and end date
- Updated service with previous month
**Jira Link** - https://bahmni.atlassian.net/jira/software/c/projects/BAH/boards/25?selectedIssue=BAH-3175
**Screenshot**
> BAH-3175 | Samridhi | Add Previous Month option in Bahmni Reports pre-filter

- micro-frontends/src/next-ui/Components/ViewObservationForm/viewObservationForm.scss
Minor feedback on View Observation Form
> Ayush | 1205496493983199 | UI feedback for view observation form

- micro-frontends/src/next-ui/Components/AddAllergy/AddAllergy.jsx
- micro-frontends/src/next-ui/Components/AddAllergy/__snapshots__/AddAllergy.spec.jsx.snap
- micro-frontends/src/next-ui/Components/SearchAllergen/SearchAllergen.jsx
- micro-frontends/src/next-ui/Components/SearchAllergen/__snapshots__/SearchAllergen.spec.jsx.snap
- micro-frontends/src/next-ui/Components/SelectReactions/SelectReactions.jsx
- micro-frontends/src/next-ui/Components/SelectReactions/__snapshots__/SelectReactions.spec.jsx.snap
- micro-frontends/src/next-ui/Containers/patientAlergies/PatientAlergiesControl.jsx
- micro-frontends/src/next-ui/Containers/patientAlergies/patientAllergiesControl.scss
- micro-frontends/src/styles/common.scss
- ui/app/clinical/common/controllers/visitController.js
- ui/app/clinical/common/views/providerInfo.html
- ui/app/common/displaycontrols/admissiondetails/directives/admissionDetails.js
- ui/app/common/displaycontrols/admissiondetails/views/admissionDetails.html
- ui/app/i18n/clinical/locale_en.json
- ui/test/unit/clinical/common/controllers/visitController.spec.js
Jira --> https://bahmni.atlassian.net/jira/software/c/projects/BAH/boards/55?modal=detail&selectedIssue=BAH-3233
> BAH-3233 | Discharge summary configuration

- ui/app/clinical/consultation/services/exitAlertService.js
- ui/app/common/attributeTypes/views/attributeInformation.html
- ui/app/common/domain/services/programService.js
- ui/app/common/ui-helper/controllers/messageController.js
- ui/app/common/uicontrols/programmanagement/controllers/manageProgramController.js
- ui/app/common/uicontrols/programmanagement/directive/programAttributes.js
- ui/app/common/uicontrols/programmanagement/views/programRow.html
- ui/test/unit/clinical/consultation/services/exitAlertService.spec.js
- ui/test/unit/common/uicontrols/programmanagement/controllers/manageProgramController.spec.js
Asana - https://app.asana.com/0/1204322126657135/1205463335092754
This PR has changes to
- Hide program outcome field based on configuration
- Fix dependency issue (resolved by product team) for error messages in Consultation section
- Bring up the dropdown fields for Openmrs Concept datatypes
> Arjun | A-1205463335092754 | Feedback [Triage program/Pre-patient flow]

- ui/Gruntfile.js
- ui/app/clinical/common/controllers/visitController.js
- ui/app/common/displaycontrols/admissiondetails/directives/admissionDetails.js
- ui/app/common/displaycontrols/diagnosis/directives/bahmniDiagnosis.js
- ui/app/common/displaycontrols/observation/directives/bahmniObservation.js
- ui/app/common/displaycontrols/prescription/directives/prescription.js
- ui/app/common/obs/directives/showObservation.js
- ui/app/common/ui-helper/printer.js
JIRA ref : [BAH-3244](https://bahmni.atlassian.net/browse/BAH-3244)
> BAH-3244 | adds printing based on custom templates and configs

- ui/app/clinical/displaycontrols/allvisits/views/visitsTable.html
JIRA -> [BAH-3166](https://bahmni.atlassian.net/browse/BAH-3166)
In this PR, the `isOneDayVisit` method has been call to validate if the `startDate` and `stopDate` is the same, and in that the display only the `startDate` for that visit.
> BAH-3166 | Fix. Same Day Visit Display Format

- micro-frontends/public/i18n/locale_en.json
- micro-frontends/src/next-ui/Containers/patientAlergies/PatientAlergiesControl.jsx
- micro-frontends/src/next-ui/Containers/patientAlergies/PatientAlergiesControl.spec.jsx
- ui/app/i18n/clinical/locale_en.json
Tanya| UAT Feedback| A-https://app.asana.com/0/1204322126657135/1205463742623492
> UAT Feedback

- ui/app/clinical/consultation/views/treatmentSections/drugOrderHistory.html
Jira card - [https://bahmni.atlassian.net/browse/BAH-3247](https://bahmni.atlassian.net/browse/BAH-3247)
> Sri Laxmi | BAH-3247 | MOBN-2203 | Adding time to medication prescription.

- ui/app/clinical/common/controllers/visitController.js
- ui/app/clinical/consultation/views/bacteriology.html
- ui/app/common/ui-helper/directives.js
- ui/app/common/util/dateUtil.js
- ui/app/reports/views/myReports.html
- ui/test/unit/clinical/common/controllers/visitController.spec.js
- ui/test/unit/common/displaycontrols/obsVsObsFlowSheet/directives/obsToObsFlowSheet.spec.js
- ui/test/unit/common/displaycontrols/orders/directives/ordersControl.spec.js
- ui/test/unit/common/domain/mappers/observationValueMapper.spec.js
- ui/test/unit/common/models/age.spec.js
- ui/test/unit/common/obs/directives/showObservation.spec.js
- ui/test/unit/common/obs/observation.spec.js
- ui/test/unit/common/uicontrols/programmanagement/controllers/manageProgramController.spec.js
- ui/test/unit/common/util/dateUtil.spec.js
- ui/test/unit/reports/controllers/myReportsController.spec.js
cherry-picker commit from product to change year format from YY to YYYY
> Maha | BAH-3245 | year format change across all modules

- ui/app/common/displaycontrols/programs/directives/programs.js
Asana - https://app.asana.com/0/1204322126657135/1205664913179288
> Arjun | A-1205664913179288 | Speciality field is showing json object instead of a single value

- ui/app/common/displaycontrols/admissiondetails/directives/admissionDetails.js
- ui/app/common/patient-search/controllers/patientsListController.js
Asana - https://app.asana.com/0/1204322126657135/1205664708270921
Changes for the bug in programs page is also present in this bug card - https://app.asana.com/0/1204322126657135/1205664708270913
> Arjun | A-1205664708270921 | Getting Error in patient dashboard (undefined AdmissionDetails)

- ui/app/clinical/consultation/views/bacteriology.html
JIRA -> https://bahmni.atlassian.net/browse/BAH-3265
We encountered an error when navigating from the bacteriology tab due to the bacteriology form returning as 'undefined.' This issue has been resolved in this PR.
> BAH-3265 | Fix. Error due to bacteriology form

- ui/app/clinical/common/controllers/visitController.js
- ui/app/clinical/common/views/visitSummary.html
Asana - https://app.asana.com/0/1204322126657135/1205474115440282
> Arjun | A-1205474115440282 | Hide patient info in visits page

- micro-frontends/src/next-ui/Containers/patientAlergies/PatientAlergiesControl.jsx
> Arjun | changes to remove patient dashboard errors

- ui/app/common/displaycontrols/dashboard/directives/dashboard.js
> Arjun | Fix error message on ADT page

- micro-frontends/src/next-ui/Components/EditObservationForm/EditObservationForm.jsx
- micro-frontends/src/next-ui/Components/EditObservationForm/EditObservationFormUtils.js
Asana - https://app.asana.com/0/1204322126657135/1205754462895423
> Arjun | A-1205754462895423 | Unwanted entries in forms showing up in edit view

- ui/app/admin/controllers/orderTemplateController.js
JIRA : https://bahmni.atlassian.net/browse/BS-282
> BS-282 | Adding Drug Reference Maps to Order set member

- ui/app/clinical/common/services/cdssService.js
- ui/app/clinical/consultation/controllers/addTreatmentController.js
- ui/app/clinical/consultation/controllers/diagnosisController.js
- ui/app/clinical/consultation/controllers/drugOrderHistoryController.js
- ui/app/clinical/consultation/controllers/treatmentController.js
- ui/app/clinical/consultation/directives/cdssAlertRow.js
- ui/app/clinical/consultation/views/cdssAlertRow.html
- ui/app/clinical/consultation/views/cdssPopover.html
- ui/app/clinical/consultation/views/conditionRow.html
- ui/app/clinical/consultation/views/conditions.html
- ui/app/clinical/consultation/views/diagnosis.html
- ui/app/clinical/consultation/views/diagnosisAlertRow.html
- ui/app/clinical/consultation/views/diagnosisRow.html
- ui/app/clinical/consultation/views/treatmentSections/drugOrderHistory.html
- ui/app/styles/clinical/_diagnosis.scss
Jira - https://bahmni.atlassian.net/browse/BS-281
Fixed bugs related to CDSS alerts on diagnosis/conditions and medications tabs.
> BS-281 | CDSS Observations for all the interactions

- ui/app/clinical/common/services/cdssService.js
- ui/app/clinical/consultation/controllers/diagnosisController.js
- ui/app/clinical/consultation/directives/cdssAlertRow.js
Jira - https://bahmni.atlassian.net/browse/BS-281
- Remove/recompute the alerts for removed diagnosis
- Remove empty diagnosis from CDSS payload
> BS281 | CDSS Observations for all the interactions

- ui/app/ot/services/surgicalAppointmentService.js
- ui/test/unit/ot/services/surgicalAppointmentService.spec.js
https://app.asana.com/0/1204322126657135/1205831568550570
This PR has changes to modify custom attributes to print person gender and DOB in OT surgical block list view print feature.
> Phani / Arjun | A-1205831568550570 | Update custom attributes in OT surgical block

- ui/app/clinical/consultation/views/diagnosisRow.html
- ui/app/styles/clinical/_diagnosis.scss
Jira - https://bahmni.atlassian.net/browse/BS-289
- Added back padding for saved diagnosis names
> BS-281 | Fix saved diagnosis padding

- ui/app/clinical/common/services/cdssService.js
- ui/app/clinical/consultation/controllers/diagnosisController.js
- ui/test/unit/clinical/consultation/controllers/diagnosisController.spec.js
- ui/test/unit/clinical/consultation/services/cdssService.spec.js
- ui/test/unit/clinical/controllers/addTreatmentController.spec.js
Fixed issue on showing alerts for descendants of diagnosis and same substance drugs for drug diagnosis
> Bug bash issue 4 8

- ui/app/adt/app.js
- ui/app/adt/controllers/adtController.js
- ui/app/adt/views/dashboard.html
- ui/app/adt/views/headerAdt.html
- ui/app/clinical/common/controllers/visitController.js
- ui/app/clinical/common/controllers/visitHeaderController.js
- ui/app/clinical/common/services/clinicalAppConfigService.js
- ui/app/clinical/common/views/visit.html
- ui/app/clinical/common/views/visitHeader.html
- ui/app/common/patient/header/views/header.html
- ui/test/unit/clinical/common/controllers/visitHeaderController.spec.js
- ui/yarn.lock
This PR adds the ability to toggle the IPD features.
1. In Clinical & In Patient App config: 
When `enableIPDFeature` is set to true -> New React IPD Dashboard is shown.
When `enableIPDFeature` is set to false -> Angular Visit Summary is shown.
2. Add to Drug chart option in treatments display control is only shown when `enableIPDFeature` is shown.
> Phani | A-1205860129671186 | Add a feature toggle for ipd features

- ui/app/admin/controllers/fhirExportController.js
- ui/app/admin/services/fhirExportService.js
- ui/test/unit/admin/controllers/fhirExportController.spec.js
Filter only FHIR Export tasks in Admin FHIR Export UI
https://bahmni.atlassian.net/browse/BS-292
> BS 292 -  Filter only FHIR Export tasks in Admin FHIR Export UI

- micro-frontends/src/next-ui/Components/ViewObservationForm/ViewObservationForm.jsx
- micro-frontends/src/next-ui/Components/ViewObservationForm/viewObservationForm.scss
- micro-frontends/src/next-ui/Containers/formDisplayControl/FormDisplayControl.jsx
- ui/app/clinical/common/controllers/visitController.js
- ui/app/clinical/common/views/formPrint.html
- ui/app/clinical/consultation/controllers/drugOrderHistoryController.js
- ui/app/clinical/index.html
- ui/app/common/displaycontrols/dashboard/directives/dashboard.js
- ui/app/common/displaycontrols/forms/directives/formsTable.js
- ui/app/common/displaycontrols/forms/views/formsTable.html
- ui/app/common/displaycontrols/forms/views/showObservationFormData.html
- ui/app/common/displaycontrols/observation/directives/bahmniObservation.js
- ui/app/common/services/formPrintService.js
- ui/app/styles/clinical/_patientDashboard.scss
- ui/test/unit/common/displaycontrols/dashboard/Directives/dashboard.spec.js
- ui/test/unit/common/displaycontrols/forms/directives/formsTable.spec.js
- ui/test/unit/common/displaycontrols/observation/directives/bahmniObservation.spec.js
- ui/test/unit/common/services/formPrintService.spec.js
JIRA : [BAH-3334](https://bahmni.atlassian.net/browse/BAH-3334)
Sample Screenshot:
> BAH-3334 | Print feature for forms display control

- micro-frontends/src/next-ui/Containers/formDisplayControl/FormDisplayControl.jsx
- ui/app/adt/index.html
- ui/app/bedmanagement/index.html
- ui/app/clinical/index.html
- ui/app/common/services/allergyService.js
- ui/app/orders/index.html
- ui/app/registration/index.html
- ui/test/unit/clinical/controllers/drugOrderHistoryController.spec.js
- ui/test/unit/common/services/formPrintService.spec.js
- fixes injector error in all modules due to formPrintService script
- fixes showing different form's data in the view form of orthopaedic report
> Kavitha | BAH-3334 | fix import error and view form issue

- ui/app/common/concept-set/services/conceptSetServices.js
JIRA : https://bahmni.atlassian.net/browse/BAH-3266
> BAH-3266 | Removing locale param from concept search by SearchByFullName api call

- ui/app/adt/views/dashboard.html
- ui/app/clinical/common/views/visit.html
- ui/app/clinical/common/views/visitHeader.html
After adding toggle to new IPD page, The Action Buttons in Patient Movement section are not coming up. 
This PR fixes this issue
> Phani | Fix Missing ADT Admit/Transfer buttons

- ui/app/clinical/common/models/drugOrderViewModel.js
- ui/app/clinical/consultation/models/drugOrderOptions.js
- ui/test/unit/clinical/models/drugOrderViewModel.spec.js
Asana: https://app.asana.com/0/1204322126657135/1205821184257091/f
> update. duration unit and duration based on frequency

- micro-frontends/src/ipd/IpdDashboard.jsx
- ui/app/adt/constants.js
- ui/app/adt/controllers/adtController.js
- ui/app/adt/controllers/wardListController.js
- ui/app/adt/views/dashboard.html
- ui/app/clinical/app.js
- ui/app/clinical/common/controllers/visitController.js
- ui/app/clinical/common/controllers/visitHeaderController.js
- ui/app/clinical/common/models/auditLogEventDetails.js
- ui/app/clinical/common/views/visit.html
- ui/app/clinical/common/views/visitHeader.html
- ui/app/clinical/common/views/visitIpd.html
- ui/app/clinical/displaycontrols/allvisits/directives/visitsTable.js
- ui/test/unit/adt/controllers/wardListController.spec.js
- ui/test/unit/clinical/displaycontrols/visitsTable.spec.js
https://app.asana.com/0/1204322126657135/1206201729443040
This PR has changes to
- create new page for IPD dashboard as discussed
- handle redirections to and from the screen
> A-1206201729443040 | Navigation to clinical dashboard and discharge summary tab from IPD dashboard

- micro-frontends/src/ipd/IpdDashboard.jsx
- ui/app/adt/controllers/adtController.js
- ui/app/clinical/common/controllers/visitController.js
A-1205892749342345 | Ability to update scheduled medication task with the administered time from the right side slider (based on the configurable dosing window) and refresh the Nursing Tasks display control in new IPD dashboard
> Update Schedule Medication

- ui/app/clinical/consultation/controllers/drugOrderHistoryController.js
Asana - https://app.asana.com/0/1204322126657135/1206293736141146
> A-1206293736141146 | Getting an error while navigating back from IPD dashboard to Medication Tab

- ui/app/clinical/common/controllers/visitController.js
A-1205810604262869 | Refreshing the 'Treatments' display control under different scenarios of 'Add to Drug Chart' link, along with Edit Drug Chart scenario
> Add visit uuid and visit summary to hostdata

- ui/app/common/util/dateUtil.js
- ui/test/unit/ot/services/surgicalAppointmentService.spec.js
BAH-3439 || Change the timezone of birthtime.
> BAH-3439 || Read also the timezone of birthtime.

- ui/app/clinical/displaycontrols/allvisits/directives/visitsTable.js
Asana : https://app.asana.com/0/1204322126657135/1206375524787702/f
> Abi | Fix. Active OPD visit redirection to IPD dashboard

- micro-frontends/src/next-ui/Components/ProviderNotificationPatients/PatientsList.scss
- micro-frontends/src/next-ui/Containers/providerNotifications/ProviderNotifications.scss
A - 1206191729016207, Provider Acknowledgement workflow for the Emergency medication administered by Ward Nurse
> [Sri] - fix styling issue for provider acknowledgement flow

- micro-frontends/yarn.lock
- ui/app/home/loginInitialization.js
Product PR - https://github.com/Bahmni/openmrs-module-bahmniapps/pull/832
> BAH-2407-update | Login error cherry-pick to IPD-master

- ui/app/clinical/common/controllers/visitController.js
- ui/app/clinical/displaycontrols/allvisits/directives/visitsTable.js
Asana Card: https://app.asana.com/0/1204322126657135/1206293697979002/f
> Enable read mode for inactive ipd visit

- micro-frontends/package.json
- micro-frontends/src/next-ui/Components/ProviderNotificationPatients/PatientListContent.jsx
- micro-frontends/src/next-ui/Components/ProviderNotificationPatients/PatientListMockData.js
- micro-frontends/src/next-ui/Components/ProviderNotificationPatients/PatientListTitle.jsx
- micro-frontends/src/next-ui/Components/ProviderNotificationPatients/PatientListTitle.scss
- micro-frontends/src/next-ui/Components/ProviderNotificationPatients/PatientListTitle.spec.jsx
- micro-frontends/src/next-ui/Components/ProviderNotificationPatients/PatientsList.jsx
- micro-frontends/src/next-ui/Components/ProviderNotificationPatients/PatientsList.spec.jsx
- micro-frontends/src/next-ui/utils/providerNotifications/ProviderNotificationUtils.js
- micro-frontends/src/next-ui/utils/providerNotifications/ProviderNotificationUtils.spec.js
- micro-frontends/src/next-ui/utils/utils.js
- micro-frontends/src/next-ui/utils/utils.spec.js
- micro-frontends/yarn.lock
Story no - 1206522048129442 
Patient with the earliest notification should be listed first.
Inside patient accordion, the earliest notification should be listed first.
When user clicks on the patient ID, targeted tab should open 
The way patient details are mentioned, should be similar to other pages
> [ Sri ] : A 1206522048129442 | Refactor the patient list view in the provider acknowledgement flow

- ui/app/clinical/config/visitMandatoryTab.json
- ui/app/i18n/clinical/locale_en.json
JIRA -> [BAH-3523](https://bahmni.atlassian.net/browse/BAH-3523)
> BAH-3523 | Refactor. Change Radiology Display Control Title in Visit Summary Screen

- ui/app/clinical/consultation/controllers/diagnosisController.js
- ui/app/common/constants.js
- ui/app/common/domain/services/diagnosisService.js
- ui/test/unit/clinical/consultation/controllers/diagnosisController.spec.js
A - 1206597157227832 | Fetch diagnosis Sugesstion Limit from config
> [Sri] - Fetch diagnosis Sugesstion Limit from config

- ui/app/clinical/consultation/services/treatmentConfig.js
- removes default rule names from the dosage rule dropdown based on config
> Kavitha | add configurable default dosage rules for medications

- ui/app/clinical/consultation/controllers/diagnosisController.js
- ui/app/common/domain/services/diagnosisService.js
- ui/test/unit/clinical/consultation/controllers/diagnosisController.spec.js
This reverts commit 3ec33c52d2379d3eab0cce070f535f45927d62f7, reversing changes made to 7ae22454324dc38e8f5c2b936b25c78b4ed3cfe9.
> Revert "Merge pull request #845 from Bahmni/ftr/1206597157227832"

- ui/app/clinical/consultation/controllers/diagnosisController.js
- ui/app/clinical/consultation/views/diagnosis.html
- ui/test/unit/clinical/consultation/controllers/diagnosisController.spec.js
JIRA -> [BAH-3567](https://bahmni.atlassian.net/browse/BAH-3567)
In this PR, we had fixed unexpected server error message when adding an existing Diagnosis by showing proper error message for duplicate diagnosis.
> BAH-3567 | Fix. Unexpected Server Error When Adding an Existing Diagnosis 

- ui/app/clinical/consultation/views/treatmentSections/addTreatment.html
- calculates dosage based on rules only when the mandatory fields are filled
> Kavitha | fix wrong dose calculation for rules

- micro-frontends/package.json
Asana: https://app.asana.com/0/1204322126657135/1206514082919772/f
> update. bahmni-carbon-ui version

- ui/app/common/constants.js
- ui/app/common/util/dateUtil.js
- ui/test/unit/common/util/dateUtil.spec.js
PR -> [BAH-3522](https://bahmni.atlassian.net/browse/BAH-3522)
This PR introduces functions to convert a dateTime from UTC to local time in the front-end dateTime format. Additionally, it adds a constant to specify formats globally.
> BAH-3522 | Add. Date Time Parser In Local Time

- ui/app/clinical/consultation/controllers/addTreatmentController.js
- ui/app/clinical/consultation/views/newDrugOrders.html
- ui/app/clinical/consultation/views/treatmentSections/addTreatment.html
- ui/app/clinical/consultation/views/treatmentSections/drugOrderHistory.html
- makes frequency, duration and total quantity in the medications tab optional when the route is chosen from the configurable continuous medications routes (Intravenous/Inhalation)
JIRA ref: [BAH-3629](https://bahmni.atlassian.net/browse/BAH-3629)
> BAH-3629 | Kavitha | optional fields for continuous medication

- ui/app/clinical/consultation/controllers/addTreatmentController.js
- ui/app/clinical/consultation/views/treatmentSections/addTreatment.html
- ui/app/i18n/clinical/locale_en.json
- ui/test/unit/clinical/controllers/addTreatmentController.spec.js
Asana - https://app.asana.com/0/1204322126657135/1206630318406475
> A-1206630318406475 | If Patient's weight is not captured, System should not allow Doctor's to save Rx

- ui/app/common/concept-set/models/observationNode.js
JIRA -> [BAH-3544](https://bahmni.atlassian.net/browse/BAH-3544)
> BAH-3544 | Fix. Accept Button Issue in H&E Form

- .github/scripts/transifex.sh
- .github/workflows/build_publish.yml
- .github/workflows/pull_translations.yml
This workflow is designed to retrieve translations from Transifex once every month in case resources are updated.
> BAH-3644 | Add. Workflow To Pull Translations

- ui/app/orders/controllers/orderFulfillmentController.js
Asana - https://app.asana.com/0/1204322126657135/1206686118266446
> A-1206686118266446 | Creating queue for Rehab orders

- ui/app/common/domain/services/visitDocumentService.js
- ui/app/common/ui-helper/services/messagingService.js
- ui/app/i18n/document-upload/locale_en.json
- ui/test/unit/common/domain/services/visitDocumentService.spec.js
JIRA -> [BAH-2833](https://bahmni.atlassian.net/browse/BAH-2833)
This PR handles the 413, Request Entity Too Large error which will be thrown when we try to upload a document having size greater than the configured size limit and also displays an error message in the ui.
> Parvathy | BAH-2833 | Display Error Message When Document Size Limit Exceeds

- ui/app/common/domain/services/visitDocumentService.js
- ui/app/i18n/document-upload/locale_en.json
JIRA -> [BAH-2833](https://bahmni.atlassian.net/browse/BAH-2833)
> Parvathy | BAH-2833 | Fix. Handle Document Size Limit Error Message

- micro-frontends/src/next-ui/Components/ViewAllergiesAndReactions/ViewAllergiesAndReactions.jsx
- micro-frontends/src/next-ui/Components/ViewAllergiesAndReactions/ViewAllergiesAndReactions.spec.jsx
- micro-frontends/src/next-ui/Components/ViewAllergiesAndReactions/__snapshots__/ViewAllergiesAndReactions.spec.jsx.snap
- micro-frontends/src/next-ui/Containers/patientAlergies/PatientAlergiesControl.jsx
- ui/app/registration/directives/patientRelationship.js
- ui/app/registration/initialization.js
- ui/app/registration/views/patientRelationships.html
- ui/test/unit/registration/directives/patientRelationshipController.spec.js
Asana Link: https://app.asana.com/0/1204322126657135/1206805583921910/f
> Fix allergies and relationship

- ui/app/adt/controllers/careViewController.js
- ui/app/clinical/common/controllers/visitController.js
- ui/app/common/auth/authentication.js
- ui/app/registration/controllers/navigationController.js
Asana link: https://app.asana.com/0/1204322126657135/1206917401901476
> IPD Feedback Set-1

- micro-frontends/src/next-ui/Components/EditObservationForm/EditObservationForm.jsx
- micro-frontends/src/next-ui/Components/EditObservationForm/EditObservationForm.spec.jsx
- micro-frontends/src/next-ui/Components/EditObservationForm/EditObservationFormUtils.js
- micro-frontends/src/next-ui/Components/ViewObservationForm/ViewObservationForm.jsx
- micro-frontends/src/next-ui/Components/ViewObservationForm/ViewObservationForm.spec.jsx
- micro-frontends/src/next-ui/Components/ViewObservationForm/__snapshots__/ViewObservationForm.spec.jsx.snap
- micro-frontends/src/next-ui/Containers/formDisplayControl/FormDisplayControl.jsx
- micro-frontends/src/next-ui/Containers/formDisplayControl/FormDisplayControl.spec.jsx
- micro-frontends/src/next-ui/Containers/formDisplayControl/FormDisplayControlMockData.js
- micro-frontends/src/next-ui/utils/FormDisplayControl/FormUtils.js
- integrates form name translations based on locale in the react form2 display control
> Kavitha| Form name translations in Form2 display control

- ui/app/styles/registration/_registration.scss
Asana : https://app.asana.com/0/1204322126657135/1206880111181067/f
> update. style for observation widget in registeration page

- ui/app/styles/clinical/_orders.scss
Asana: https://app.asana.com/0/1204322126657135/1206928043940765/f
> update. width of the provider date

- ui/app/clinical/consultation/controllers/addTreatmentController.js
- ui/app/i18n/clinical/locale_en.json
- ui/test/unit/clinical/controllers/addTreatmentController.spec.js
https://app.asana.com/0/1204322126657135/1206821897786325
> Arjun | Doctor should not be able to prescribe medicine unless diagnosis is captured

- ui/app/clinical/consultation/controllers/addTreatmentController.js
- ui/test/unit/clinical/controllers/addTreatmentController.spec.js
Changing the configs needs a change in ui level to toggle the feature
> Arjun | refactor treatments capture for diagnosis 

- micro-frontends/src/next-ui/Components/EditObservationForm/EditObservationForm.jsx
A-1207088245670247| [CURE Bug] - Getting null error while editing the form | https://app.asana.com/0/1204322126657135/1207088245670247/
> Tanya | set orders as empty when editing from clinical dashboard

- ui/app/adt/controllers/careViewController.js
- ui/app/clinical/common/controllers/visitController.js
- ui/app/common/auth/authentication.js
- ui/app/registration/controllers/navigationController.js
A-1207130871600195 | Feedback work - addressing Rx Future Start Date in PRN and non-PRN Workflows & retaining ward context of Nurse | https://app.asana.com/0/1204322126657135/1207130871600195/
> Retain ward context on logout

- ui/app/common/ui-helper/header.html
- ui/app/i18n/orders/locale_en.json
- ui/app/orders/controllers/orderFulfillmentController.js
- ui/app/orders/views/orderFulfillment.html
- ui/app/styles/bahmni-layout/_layout.scss
- ui/app/styles/clinical/_orders.scss
- ui/app/styles/common/_bahmniGlobal.scss
- ui/test/unit/orders/controllers/orderFulfillmentController.spec.js
JIRA Card https://bahmni.atlassian.net/browse/BAH-3070
> BAH-3070 | Ability to take ownership of radiology orders

- ui/app/ot/controller/calendarViewController.js
- ui/app/ot/controller/otCalendarController.js
- ui/app/ot/views/home.html
- ui/app/ot/views/otCalendar.html
- ui/app/styles/ot/_ot.scss
- ui/app/styles/ot/_otCalendar.scss
- ui/test/unit/ot/controller/otCalendarController.spec.js
JIRA link -> [https://bahmni.atlassian.net/browse/BAH-3050](https://bahmni.atlassian.net/browse/BAH-3050)
> BAH-3050 | add provider based OT view and date picker 

- micro-frontends/src/next-ui/Containers/formDisplayControl/FormDisplayControl.jsx
- micro-frontends/src/next-ui/Containers/formDisplayControl/FormDisplayControl.spec.jsx
- micro-frontends/src/next-ui/Containers/formDisplayControl/FormDisplayControlMockData.js
- micro-frontends/src/next-ui/utils/FormDisplayControl/FormView.js
Asana Link: https://app.asana.com/0/1204322126657135/1207086955567542/f
> Form view and edit based on privilege

- ui/app/common/displaycontrols/navigationlinks/directives/navigationLinks.js
- ui/app/common/patient-search/controllers/patientsListController.js
- ui/test/unit/common/patient-search/controllers/patientsListController.spec.js
JIRA Card - [https://bahmni.atlassian.net/browse/BAH-3200](https://bahmni.atlassian.net/browse/BAH-3200)
> Abi, Kavitha | BAH-3200 | add targeted tab feature for queues

- ui/app/i18n/registration/locale_en.json
- ui/app/registration/controllers/searchPatientController.js
- ui/app/registration/directives/patientAction.js
- ui/app/registration/views/search.html
JIRA Card - [https://bahmni.atlassian.net/browse/BAH-3803](https://bahmni.atlassian.net/browse/BAH-3803)
> Umair, kavitha | BAH-3803 |Display patient search results based on the configuration

- .tx/config
JIRA -> [BAH-3824](https://bahmni.atlassian.net/browse/BAH-3824)
In this PR, a new resource for the micro-frontend subfolder has been created and added to Transifex. The tx-config file has been updated to include the newly added resource, ensuring that it is included in the localization process.
> BAH-3824 | Add. Transifex Resource For Micro-Frontend

- ui/app/clinical/common/controllers/visitController.js
- ui/app/clinical/common/services/allergyService.js
- ui/app/clinical/consultation/controllers/drugOrderHistoryController.js
- ui/app/clinical/consultation/controllers/treatmentController.js
- ui/app/clinical/consultation/views/treatment.html
- ui/app/common/displaycontrols/dashboard/directives/dashboard.js
- ui/app/common/displaycontrols/dashboard/views/dashboard.html
- ui/app/styles/clinical/treatment/_treatment.scss
- ui/test/unit/clinical/common/services/allergyService.spec.js
- ui/test/unit/clinical/consultation/controllers/treatmentController.spec.js
JIRA Card -> [https://bahmni.atlassian.net/browse/BAH-3743](https://bahmni.atlassian.net/browse/BAH-3743)
> Phani | BAH-3743 | Ability to show display controls in consultation Medications tab

- ui/app/clinical/common/controllers/visitController.js
- ui/app/clinical/common/services/allergyService.js
- ui/app/clinical/consultation/controllers/drugOrderHistoryController.js
- ui/test/unit/clinical/common/services/allergyService.spec.js
JIRA -> [BAH-3743](https://bahmni.atlassian.net/browse/BAH-3743)
In this PR, the missing `allergyPromise` declaration is added to resolve the run time error.
> BAH-3743 | Fix. Missing Allergy Promise Init

- ui/app/clinical/common/models/drugOrderViewModel.js
- ui/app/clinical/consultation/controllers/addTreatmentController.js
- ui/app/clinical/consultation/controllers/drugOrderHistoryController.js
- ui/app/clinical/consultation/models/drugOrderOptions.js
- ui/app/clinical/consultation/services/treatmentConfig.js
- ui/app/clinical/consultation/views/treatmentSections/addTreatment.html
- ui/app/clinical/consultation/views/treatmentSections/drugOrderHistory.html
- ui/app/common/domain/services/diagnosisService.js
- ui/app/i18n/clinical/locale_en.json
- ui/app/styles/clinical/_visit.scss
- ui/app/styles/clinical/treatment/_treatment.scss
- ui/test/unit/clinical/controllers/addTreatmentController.spec.js
- ui/test/unit/clinical/controllers/drugOrderHistoryController.spec.js
- ui/test/unit/clinical/displaycontrols/visitsTable.spec.js
- ui/test/unit/clinical/models/drugOrderViewModel.spec.js
JIRA card -> [https://bahmni.atlassian.net/browse/BAH-3849](https://bahmni.atlassian.net/browse/BAH-3849)
> Arjun, Ashish | BAH-3849 | Enhancements on Medication Page

- ui/app/adt/index.html
- ui/app/bedmanagement/index.html
- ui/app/common/config/services/configurations.js
- ui/test/unit/common/config/services/configurations.spec.js
JIRA -> [BAH-3870](https://bahmni.atlassian.net/browse/BAH-3870)
In this PR, the broken dashboard view In ADT and Bed Management is fixed.
> BAH-3870 | Fix. Missing ConsultationMapper In ADT

- ui/app/clinical/consultation/views/treatmentSections/drugOrderHistory.html
Bug link : https://app.asana.com/0/1204322126657135/1207388697706368
> Kavitha | fix opening print view when check box and edit is selected

- ui/app/admin/index.html
- ui/app/admin/initialization.js
- ui/app/admin/views/header.html
- ui/app/adt/views/headerAdt.html
- ui/app/bedmanagement/initialization.js
- ui/app/bedmanagement/views/header.html
- ui/app/common/ui-helper/header.html
- ui/app/document-upload/app.js
- ui/app/document-upload/initialization.js
- ui/app/document-upload/views/patientHeader.html
- ui/app/i18n/document-upload/locale_en.json
- ui/app/i18n/ipd/locale_en.json
- ui/app/i18n/reports/locale_en.json
- ui/app/ot/index.html
- ui/app/ot/initialization.js
- ui/app/ot/views/header.html
- ui/app/reports/initialization.js
- ui/app/reports/views/dashboardHeader.html
JIRA -> [BAH-3968](https://bahmni.atlassian.net/browse/BAH-3968)
In this PR, quick logout support has been added to Admin, Bed Management, Doc, OT And Reports. The quick logout feature uses a shortcut key combination (Cmd/Ctrl + Esc) by default for logout. This is driven by configuration and can be set by adding a new global property `quickLogoutComboKey`.
>  BAH-3968 | Add. Quick Logout Support In Admin, Bed, Doc, OT And Reports

- ui/app/registration/initialization.js
- adds null check for person in relationship type map in the registration initialization
> Kavitha| add null check for person in relationship type map

- ui/app/clinical/common/controllers/visitController.js
JIRA -> [BAH-3990](https://bahmni.atlassian.net/browse/BAH-3990)
In this PR, the handleAuditEvent function has been added to the hostApi in IpdDashboard, addressing the issue encountered when adding a drug to the drug chart. With this change, the drug will get added to the drug chart without refreshing the UI, Also, it ensures that audit logs are correctly recorded for IPD activities.
> BAH-3990 | Fix. Added handleAuditEvent function to hostApi in IpdDashboard

- ui/app/clinical/common/controllers/visitController.js
- ui/app/common/displaycontrols/admissiondetails/directives/admissionDetails.js
JIRA -> [BAH-4015](https://bahmni.atlassian.net/browse/BAH-4015)
In this PR, null checks have been added to the Provider and VisitSummary to fix the errors thrown in the IPD dashboard and patient dashboard.
> BAH-4015 | Fix. Null Check for Provider and VisitSummary

- ui/app/styles/registration/_registration.scss
Reverts Bahmni/openmrs-module-bahmniapps#924
> Revert "Fix css for zscore lengthy text in registration 2nd page (#857)"

- ui/Gruntfile.js
- ui/app/clinical/common/views/formPrint.html
JIRA -> [BAH-3334](https://bahmni.atlassian.net/browse/BAH-3334)
In this pull request, the formPrint file path has been added to the Gruntfile for minification. This update will resolve the issue of broken form printing when a display control is requested for printing.
> BAH-3334 | Fix. Miss CSS Stylesheet In formPrint.html

- ui/app/common/constants.js
- ui/app/common/displaycontrols/dashboard/directives/dashboard.js
JIRA -> [BAH-3334](https://bahmni.atlassian.net/browse/BAH-3334)
> BAH-3334 | Fix. Incorrect Accessing Of FormV2React Config

- ui/app/common/auth/authentication.js
> BAH-3971 | Fixing code merge issue. Provider - user association was broken

- ui/app/clinical/dashboard/views/clinicalDashboardHeader.html
Asana card -> [https://app.asana.com/0/1204322126657135/1207783550713566/f](https://app.asana.com/0/1204322126657135/1207783550713566/f)
> Bindu | A-1207783550713566 | Fix undefined visitUuid issue for the Go to IPD Dashboard icon in the clinical header

- micro-frontends/package.json
- ui/package.json
JIRA -> [BAH-4097](https://bahmni.atlassian.net/browse/BAH-4097)
For Standard Release.
> BAH-4097 | Add. Bump Version Number In package.json

- ui/app/common/uicontrols/programmanagement/controllers/manageProgramController.js
- ui/app/common/uicontrols/programmanagement/directive/programAttributes.js
- ui/app/common/uicontrols/programmanagement/views/programAttributes.html
- ui/app/i18n/clinical/locale_en.json
- ui/app/i18n/clinical/locale_fr.json
- ui/test/unit/common/uicontrols/programmanagement/controllers/manageProgramController.spec.js
- ui/test/unit/common/uicontrols/programmanagement/directives/programAttributes.spec.js
https://app.asana.com/0/1204322126657135/1208424039194249
> A-1208424039194249 | Translate Program attributes in active tab

- micro-frontends/src/next-ui/Containers/patientAlergies/PatientAlergiesControl.jsx
- adds other allergies as part of the allergens
> Kavitha,Bindu| add other to the allergens

- micro-frontends/src/next-ui/Components/i18n/utils.js
https://app.asana.com/0/1204322126657135/1208586834272224
> A-1208586834272224 | Intl support for micro-frontends

- ui/app/clinical/consultation/directives/orderSelector.js
- ui/app/clinical/consultation/views/orderSelector.html
- ui/app/clinical/ordersTabInitialization.js
Order names are not showing up on UI based on the locale that app is running. This PR will fix the issue.
> Bindu | Show order names based on the locale.

- ui/package.json
- ui/yarn.lock
> [Rahul] | BAH-4131 | Add. Bump form-controls
