ui/test/unit/common/domain/services/programService.spec.js
ui/test/unit/registration/mappers/openmrsPatientMapper.spec.js

This commit fixes a few issues experience when running the test in the AEST timezone at around 20:00.
There are three other errors that I am not convinced are errors in the unit tests:
```
PhantomJS 1.9.8 (Mac OS X 0.0.0) patientMapper should map birth date in dd-mm-yyyy format FAILED
Expected '2016-01-15' to equal '2016-01-14'.
Error: Expected '2016-01-15' to equal '2016-01-14'.
at /Users/mnewman/projects/bahmni/openmrs-module-bahmniapps/ui/test/unit/registration/mappers/openmrsPatientMapper.spec.js:127
PhantomJS 1.9.8 (Mac OS X 0.0.0) patientMapper should map registration date FAILED
Expected '2016-01-15' to equal '2016-01-14'.
Error: Expected '2016-01-15' to equal '2016-01-14'.
at /Users/mnewman/projects/bahmni/openmrs-module-bahmniapps/ui/test/unit/registration/mappers/openmrsPatientMa …
```

Fixing some simple timezone issues in tests

---

ui/test/unit/common/domain/services/programService.spec.js

Update unit test to check dates against local timezone.
Otherwise, tests fail in timezones other than IST. For example, when run in Australia, programService test updatePatientProgram expects dateEnrolled : '2016-01-01T00:00:00+1000' but the returned value is dateEnrolled : '2016-01-01T00:00:00+0530'.

Charlie | Check dates against local timezone in unit test

---

ui/app/registration/controllers/patientCommonController.js
ui/app/registration/views/dob.html
ui/test/unit/registration/controllers/patientCommonController.spec.js

This adds the ability show or hide the birth time on the main registration page in a similar manner to the current "showMiddleName" functionality.
For backwards compatibility, defaults to "true"

Ability to hide birth time on registration page

---

ui/Gruntfile.js

If we don’t clean the coverage directory, we can get errors like this:
Running "coverage" task
Fatal error: Cannot read property 'length' of undefined
This is due to coverage reports being out of sync, as described in this
issue against the grunt-istanbul-coverage project:
https://github.com/daniellmb/grunt-istanbul-coverage/issues/10

add grunt clean:coverage task

---

.travis.yml
ui/test/config/karma.conf.js

A few changes:
* Works around npm/npm#14042 using
https://github.com/travis-ci/travis-ci/issues/4653#issuecomment-194051953
* Print out the npm debug log for when npm fails
* Cache the npm and bower directories to speed up the build
* Explicitly disable email notifications
* Use 'dots' reporter rather than 'progress' for Karma to keep console output smaller

Travis build config changes

---

.eslintrc

* alert, prompt, and confirm are used in Bahmni (http://eslint.org/docs/rules/no-alert)
* no-empty-label is removed in ESLint 2
* wrap-iife (http://eslint.org/docs/rules/wrap-iife) was using the
default 'outside' option, which isn't the standard being followed in
Bahmni

Change ESLint config to match current codebase

---

ui/app/clinical/app.js
ui/app/common/domain/services/observationsService.js

After OpenMRS 2.x upgrade the logic of Obs save changed. i.e when there is a change on obsTree at root level then entire tree will be replicated creating new Obs i.e the old obs uuid used to load the editobs page i.e 'patient.dashboard.observation' angular state is no more valid and the page throws exception.
To fix that we need to retrieve the revised obs when the obs is voided for replication.
This support for this is implemented in Bahmni-core and OpenMRS. Please refer to the below commits.
https://github.com/Bahmni/bahmni-core/commit/a7a25406019d21d069688e6919eb0f04e9de9c0f
https://github.com/openmrs/openmrs-core/commit/21225c255023f91c68b7466b1cdd6779fba7b598

Swathi |#3321 | Get revised latest obs for editing any obs in 'patient.dashboard.observation' angular state

---

ui/app/common/displaycontrols/tabularview/directives/obsToObsFlowSheet.js
ui/app/common/displaycontrols/tabularview/views/obsToObsFlowSheet.html
ui/app/styles/bahmni-helper/_base.scss
ui/test/unit/common/displaycontrols/obsVsObsFlowSheet/directives/obsToObsFlowSheet.spec.js

To improve the layout of some Bahmni endTB tables, we'd like to change the delimiter used when there are multiple obs in cell from a comma to a newline.  I've added the ability specify a custom delimiter via a property "obsDelimiter" that can be part of the dashboardConfig, like so:
```
"dashboardConfig": {
"groupByConcept": "Followup, Visit Date",
"templateName": "Followup Template",
"obsDelimiter": "\n",
"conceptNames": [
"Followup, Left Eye Correct Plates",
"Followup, Right Eye Correct Plates"            
]
}
```
Note that I also had to apply (via a new style I created) a "white-space: pre-line" to the sections in question to get the newline to be picked up.
Thoughts on this approach?
Card to track the progress for merge here -https://bahmni.mingle.thoughtworks.com/projects/bahmni_emr/c …

obsToObsFlowsheet: allow specification of a custom delimiter when multiple obs in a cell

---

ui/app/common/displaycontrols/drugOrderDetails/directives/drugOrderDetails.js
ui/app/common/displaycontrols/drugOrderDetails/views/drugOrderDetails.html

There was a request from the endtb team to add the "quantity" and "instructions" column to the drug order details display.
I'm not sure if this is something we want across all of Bahmni, but I am issuing this pull request in order to start discussion.  If we don't want this globally, is there a way (or can we add a way) to configure what fields appear here.  Thanks!
@deepaucksharma

sraza | mgoodrich | Add quantity and instruction fields to "drug order details" template

---

ui/app/clinical/consultation/controllers/diagnosisController.js
ui/app/clinical/consultation/views/diagnosis.html
ui/app/clinical/consultation/views/diagnosisRow.html
ui/test/unit/clinical/consultation/controllers/diagnosisController.spec.js

The condition-list won't be shown on diagnosis tab if `bahmni_config/openmrs/apps/clinical/app.json` file has a property `config.hideConditions`  set as `true`.
The condition-list will be shown if this property is not present or set to `false`.

Introduced a toggle to hide conditions list.

---

ui/app/styles/registration/_registrationSearch.scss

modified:   app/styles/registration/_registrationSearch.scss
Related to Talk thread: https://talk.openmrs.org/t/patient-search-results-table-font-seems-too-big/11887?u=mksrom

rbuisson | Shrink table font size of Patient Search results

---

ui/app/registration/views/patientcommon.html

Removed the ng-if condition on showAddressFieldsTopDown from address information sub-section heading. Details -  https://talk.openmrs.org/t/address-hierarchy-top-down-display/12138/2

Address Information sub-section heading

---

ui/app/i18n/registration/locale_en.json
ui/app/registration/views/patientcommon.html

Filling more L10n gaps, this time in the Registration app and a bit in the Home app.
**(Q)** This commit, such as the previous one (for the same JIRA task) is adding translation keys into the JSON files.
I am not sure if Transifex is just automatically updating its files from the ones on the repo or if it is supposed to be a manual process.
https://talk.openmrs.org/t/bahmni-changes-in-locale-en-json-should-i-update-transifex-as-well/14283

BAH-311: Fill L10n gaps in registration app

---

ui/app/clinical/displaycontrols/investigationresults/models/tabularLabOrderResults.js
ui/app/clinical/displaycontrols/investigationresults/views/investigationChart.html

In Investigation chart display control, Test units are displayed only when ranges are configured. 
Made changes to show units when configured irrespective of ranges.

Show Units irrespective of ranges configured

---

ui/app/clinical/consultation/controllers/consultationController.js
ui/app/common/ui-helper/views/saveConfirmation.html
ui/app/i18n/registration/locale_en.json
ui/app/registration/controllers/patientCommonController.js
ui/app/registration/views/header.html
ui/test/unit/registration/controllers/patientCommonController.spec.js

1.A confirm box has been added when ever the user tries to navigate away from the patient registration screen.
2.The above prompt is enabled through the following config being set to true in registration/app.js: "showSaveConfirmDialog" : true
3. However "stateChangeStart" and "locationChangeStart" are not getting triggered for the Home button and preventing to leverage the above functionality.
4. The desired outcome is achievable by setting an "ng-click" attribute to the Home button and calling a function when the button is clicked.Earlier this was an "id" attribute and the code to handle it was a jquery function.Due to this,a particular Code Climate test was failing as it required plain Angular code and not jQuery. The solution would have been to use "angular.element" but calling the …

BAH-497: Prompt to save if home or search clicked in registration screen

---

ui/app/appointments/constants.js
ui/app/appointments/controllers/manage/appointmentsCreateController.js
ui/app/appointments/controllers/manage/calendar/appointmentsCalendarViewController.js
ui/app/appointments/controllers/manage/list/appointmentsListViewController.js
ui/app/appointments/models/appointment.js
ui/test/unit/appointments/controllers/manage/list/appointmentsListViewController.spec.js

Fixed - If a provider is removed from an appointment, it still shows up on the views.
Fixed - not sortable by provider column in list view. now sorts only by the first provider of the appointment, hence will work as long as there is one provider for the appointment.
Also added constants. also fixed issue of wrong provider response getting recorded in certain flows of multiple provider assignment.

BAH-688, BAH-689 | Fix - Provider column sortable; Views do not show appointments for Removed/Cancelled provider responses 

---

ui/app/common/photo-capture/directives/capturePhoto.js

URL.createObjectURL() which we used to access the webcam
was deprecated in Chrome versions
prior to Chrome 71. In Chrome 71, this method was removed
and as a result a JavaScript error was thrown everytime you
try to access the Camera.
Resolves: #738

Fix camera issue with latest version of chrome

---

ui/app/common/gallery/directives/galleryPane.js
ui/app/styles/bahmni-components/_gallery.scss

Overridden by default mg-dialog css, fixing by adding a specific class to the dialog.

Patient Document Module dialog css fix

---

ui/app/clinical/displaycontrols/allvisits/directives/visitsTable.js
ui/app/common/constants.js
ui/test/unit/clinical/displaycontrols/visitsTable.spec.js

https://bahmni.atlassian.net/browse/BAH-988

Buvana, Bindu | BAH-988 | Fix visit type is not showing up in visit dashboard UAT bug

---

ui/app/common/util/httpErrorInterceptor.js

When the session is expired with OpenMRS running in docker setup, the error title has `HTTP Status 403 - Forbidden` . This causes the redirect to not happen. But the `Message` attribute in the error page is similar. So validating with it should work on both setup methods.
JIRA -> [BAH-1983](https://bahmni.atlassian.net/browse/BAH-1983)

BAH-1983 | Fix. Login redirect when session expired

---

ui/app/clinical/consultation/controllers/conceptSetPageController.js
ui/app/common/concept-set/models/observationForm.js

Form 2 forms were not  being picked as default forms under observations tab, made this change to resolve the issue.
Co-authored-by: Kavitha S <kavitha.s@thoughtworks.com>

BAH-1734 | Added extension in getting observation form

---

ui/app/common/domain/models/condition.js
ui/app/common/domain/services/conditionsService.js
ui/test/unit/clinical/models/condition.spec.js

JIRA Card -> [https://bahmni.atlassian.net/browse/BAH-2233](https://bahmni.atlassian.net/browse/BAH-2233)
As part of this PR,
-  Filtering the voided condition fields returned from conditionHistory API call
-  Filtering the conditions for which the status already changed to "History_Of"/"Inactive" as part of condition save API call

Bindu | BAH-2233 | filter the voided conditons before saving

---

ui/app/common/ui-helper/controllers/messageController.js
ui/app/common/ui-helper/messages.html

[BAH-2805](https://bahmni.atlassian.net/browse/BAH-2805) requirement was to fix "Copy Error" button which was not working for any of the pages
Seems to me that **ng-clip** and **zeroclipboard** libraries are not working as expected.
I tried it on a Plunkr 👇 and it doesn’t work there either. 
[ng-clip live example](https://embed.plnkr.co/plunk/tUXevJ)  
This problem can be resolved by leveraging window’s navigator object and copying the error text to the clipboard
I've also updated the `clip-copy` property of message button to `ng-click` since clip-copy is not working as expected.
@binduak @kk-tw @gokultw

BAH-2805 | Add fix for copy error button

---

ui/app/clinical/displaycontrols/investigationresults/views/investigationTableRow.html

This PR fixes the issue with Lab Results display in which test name is not displayed when a file is uploaded along with the lab result. 
- Replaced `test.preferredNameByLocale` with `::getLocaleSpecificNameForTest(test)`
- Removed some duplicates
Before Fix:
After Fix:

BAH-2901 | Fix. Test name when result has uploaded file

---

ui/app/clinical/consultation/models/drugSearchResult.js
ui/test/unit/clinical/models/drugSearchResult.spec.js

JIRA => https://bahmni.atlassian.net/browse/BS-148
- Even though, api call `openmrs/ws/rest/v1/drug?q=Diph+hyd&s=ordered&v=..` fetching results, we are still not returning the drugs only prefix matches.
Screenshot

BS-148 | Adding support for multiple prefix search in drug order

---

ui/app/common/ui-helper/controllers/messageController.js
ui/test/unit/common/ui-helper/controllers/messageController.spec.js

Jira card -> https://bahmni.atlassian.net/browse/BAH-2805
The issue with the copy error button in the error popup has been resolved in this PR. Previously, the button was copying the translate key instead of the error message (translate value). This PR includes the necessary fixes to ensure that the  error message is correctly copied when the button is clicked.

Parvathy | BAH-2805 | Fix. Copy Error Button

---

ui/app/adt/controllers/wardListController.js
ui/app/adt/views/wardList.html

**Context:** On ADT page, search looked up all the values coming from API. It should only search through the columns which are displayed in the grid.
- The original filter used was an Angular filter. It took a JavaScript object as input and checked if the search string is present anywhere in that object.
- The JavaScript object contains patient data such as name, age, bed number, as well as additional information like visitUUID and patientUUID.
- The behavior of the original filter was to display any patient object that had the search string present in any of its properties.
- To achieve a more specific and controlled filtering, this PR applies an additional filter. This new filter considers only certain given values (like name, age, bed number [columns present in the table]) for …

BAH-3054 | Search by a number provides incorrect results in IPD grid view

---

.github/workflows/build_publish.yml
.github/workflows/validate_pr.yml
micro-frontends/.eslintrc.js
micro-frontends/README.md
micro-frontends/jest.config.js
micro-frontends/package.json
micro-frontends/src/__mocks__/fileMock.js
micro-frontends/src/__mocks__/styleMock.js
micro-frontends/src/ipd/index.js
micro-frontends/src/next-ui/index.js
micro-frontends/src/next-ui/patientAlergies/PatientAlergiesControl.jsx
micro-frontends/src/next-ui/patientAlergies/PatientAlergiesControl.spec.jsx
micro-frontends/src/setupTests.js
micro-frontends/src/shared.js
micro-frontends/webpack.config.js
micro-frontends/yarn.lock
ui/Gruntfile.js
ui/app/clinical/dashboard/controllers/patientDashboardController.js
ui/app/clinical/dashboard/views/dashboard.html
ui/app/clinical/index.html
ui/app/clinical/init.js
ui/test/__mocks__/micro-frontends.js

This PR adds a local react micro-frontend with the angular module name "bahmni.mfe.nextUi" at location `micro-frontends/src/next-ui`. This micro-frontend will contain next gen UI elements which will be built in react.
Other notable changes:
1. the angular polyfill in micro-frontends/ has been moved to a new js file called `shared.js` which builds into `/ui/app/micro-frontends-dist/shared.min.js`
2. The above `shared` module also contains the shared styles across micro-frontends now exposed as `shared.min.css`. This contains the carbon stylesheet as well.
3. The `/micro-frontends/` react portion now supports unit tests (since local micro-frontends will be developed inside).

Local micro-frontend setup for alergies UI

---

ui/app/common/displaycontrols/patientprofile/views/patientProfile.html
ui/app/common/patient/mappers/patientMapper.js
ui/test/unit/common/patient/mappers/patientMapper.spec.js

Jira -> [BAH-3102](https://bahmni.atlassian.net/browse/BAH-3102)
In this PR, a configurable property of "additionalPatientIdentifiers" is introduced. The purpose of this is to enable the visibility of additional patient identifiers for users with the privilege to view the patient dashboard.
To implement this feature, modifications are to be made to the [openmrs/apps/clinical/dashboard.json](https://github.com/BahmniIndiaDistro/clinic-config/blob/main/openmrs/apps/clinical/dashboard.json) file. Within the "sections/patientInformation", the "additionalPatientIdentifiers" property can be configured to specify the desired additional identifiers to be displayed.
For example, if "additionalPatientIdentifiers" is set to ["ABHA Address","ABHA Number"], the patient dashboard will display these …

BAH-3102 | Add. Configurable Additional Patient Identifiers In Patient Dashboard

---

ui/app/clinical/consultation/controllers/orderController.js
ui/app/clinical/consultation/views/orderNotes.html
ui/app/common/concept-set/directives/conceptSet.js
ui/app/common/patient-search/constants.js
ui/app/common/patient-search/controllers/patientsListController.js
ui/app/i18n/clinical/locale_en.json
ui/app/orders/controllers/orderFulfillmentController.js
ui/app/orders/views/orderFulfillment.html
ui/app/styles/clinical/_orders.scss
ui/test/unit/clinical/controllers/orderController.spec.js

This PR adds options in the create notes popup while creating an order. The note after saving is then shown in the Orders module
Options and the template text:
The order after saving will show in orders section:
This PR also 
1. Removes the kid column coming up in Orders section in the patient list
2. Fixes some errors coming up in a scenario where note is empty or concept is empty

Phani | A - 1205069439065526 | Add template options for notes in lab/radiology orders

---

micro-frontends/src/ipd/DrugChartModal.jsx
micro-frontends/src/ipd/DrugChartModalNotification.jsx
micro-frontends/src/ipd/index.js
ui/app/clinical/displaycontrols/treatmentData/directives/treatmentTableRow.js
ui/app/clinical/displaycontrols/treatmentData/views/treatmentTableRow.html
ui/app/styles/clinical/_patientDashboard.scss

Asana link 
- https://app.asana.com/0/1204322126657135/1204941331551246
- https://app.asana.com/0/1204322126657135/1204941331551257
This PR has changes to
- add wrapper functions and additional callbacks for Drug chart notification and modal

BAH-3119 | Add validations and perform save in drug chart modal

---

ui/app/clinical/consultation/controllers/addTreatmentController.js
ui/app/clinical/consultation/views/treatmentSections/addTreatment.html
ui/test/unit/clinical/controllers/addTreatmentController.spec.js

Jira - https://bahmni.atlassian.net/browse/BS-160
- Display only the alert(s) related to the current drug to be added on top of the ‘Add’ button on the Medications Tab.
- For Bahmni system, use `https://fhir.openmrs.org` in the CDSS bundle payload
> <i>Only alerts relevant to the current drug are shown, despite the CDSS server's response containing alerts for other saved drugs.</i>

BS-160 | Filter and display only current medication alert

---

ui/app/clinical/consultation/controllers/addTreatmentController.js

BS-Drug Drug - Enhance FHIR CDSS Service based on Standard Format(Only Salt scope)
https://bahmni.atlassian.net/browse/BS-216

BS 216 | BS-Drug Drug - Enhance FHIR CDSS Service based on Standard Format(Only Salt scope)

---

ui/app/common/displaycontrols/pivottable/directives/pivotTable.js
ui/app/common/displaycontrols/pivottable/views/pivotTable.html

By default the rows in the Flowsheet are coming in the order of concept update DateTime, meaning which ever concept is updated last comes as first row.
In this PR based on config, If sorting this form to a specific order is needed, the data is sorted accordingly.

Phani | A-1205283475057406 | Add custom sorting for flowsheet

---

ui/app/clinical/displaycontrols/treatmentData/views/treatmentTable.html
ui/app/i18n/clinical/locale_en.json
ui/app/styles/clinical.scss

On the Patient Dashboard, Treatment Display control, when the mouse cursor hovers on share button it changes to hand icon and displays a tooltip to say: “Share or print the Prescription”.

Anuja, Vasuki | BAH-3144 | Change cursor to hand icon and display tooltip for treatments share button

---

ui/app/registration/controllers/patientCommonController.js

if some address field is retained along with the updated address fields from extension will results in the wrong address as a whole

BAH-3229 | Fix. entire address field should be cleared before updating the address from extension point

---

ui/app/clinical/common/controllers/visitController.js
ui/app/clinical/consultation/views/bacteriology.html
ui/app/common/ui-helper/directives.js
ui/app/common/util/dateUtil.js
ui/app/reports/views/myReports.html
ui/test/unit/clinical/common/controllers/visitController.spec.js
ui/test/unit/common/displaycontrols/obsVsObsFlowSheet/directives/obsToObsFlowSheet.spec.js
ui/test/unit/common/displaycontrols/orders/directives/ordersControl.spec.js
ui/test/unit/common/domain/mappers/observationValueMapper.spec.js
ui/test/unit/common/models/age.spec.js
ui/test/unit/common/obs/directives/showObservation.spec.js
ui/test/unit/common/obs/observation.spec.js
ui/test/unit/common/uicontrols/programmanagement/controllers/manageProgramController.spec.js
ui/test/unit/common/util/dateUtil.spec.js
ui/test/unit/reports/controllers/myReportsController.spec.js

JIRA -> [BAH-3245](https://bahmni.atlassian.net/browse/BAH-3245)
In this PR, the default date format has been changed to “DD-MM-YYYY”.

BAH-3245 | Fix. Set Default Date Format

---

ui/app/clinical/common/services/cdssService.js
ui/app/clinical/consultation/controllers/addTreatmentController.js
ui/app/clinical/consultation/controllers/diagnosisController.js
ui/app/clinical/consultation/directives/newDrugOrders.js
ui/app/clinical/consultation/views/cdssPopover.html
ui/app/clinical/consultation/views/diagnosis.html
ui/app/clinical/consultation/views/diagnosisRow.html
ui/app/clinical/index.html
ui/app/styles/bahmni-components/_tooltip.scss
ui/app/styles/clinical/_diagnosis.scss
ui/test/unit/clinical/consultation/controllers/diagnosisController.spec.js
ui/test/unit/clinical/consultation/services/cdssService.spec.js
ui/test/unit/clinical/controllers/addTreatmentController.spec.js

Jira: https://bahmni.atlassian.net/browse/BS-208
Display already dismissed alert message against the saved/draft Diagnosis

BS-208 | Placement of Alert near Diagnosis

---

ui/app/clinical/consultation/controllers/bacteriologyController.js
ui/app/clinical/consultation/controllers/consultationController.js
ui/test/unit/clinical/controllers/consultationController.spec.js

Asana Link: https://app.asana.com/0/1204322126657135/1205421128044324/f

Fix: Able to navigate through form 1 forms with mandatory errors

---

ui/app/clinical/common/models/drugOrderViewModel.js
ui/app/clinical/common/services/cdssService.js
ui/app/clinical/consultation/controllers/addTreatmentController.js
ui/app/clinical/consultation/controllers/consultationController.js
ui/app/clinical/consultation/controllers/diagnosisController.js
ui/app/clinical/consultation/controllers/drugOrderHistoryController.js
ui/app/clinical/consultation/controllers/treatmentController.js
ui/app/clinical/consultation/directives/cdssAlertRow.js
ui/app/clinical/consultation/directives/newDrugOrders.js
ui/app/clinical/consultation/views/cdssAlertRow.html
ui/app/clinical/consultation/views/cdssPopover.html
ui/app/clinical/consultation/views/diagnosis.html
ui/app/clinical/consultation/views/diagnosisRow.html
ui/app/clinical/consultation/views/newDrugOrders.html
ui/app/clinical/consultation/views/treatmentSections/addTreatment.html
ui/app/clinical/consultation/views/treatmentSections/drugOrderHistory.html
ui/app/clinical/index.html
ui/app/i18n/clinical/locale_en.json
ui/app/styles/bahmni-components/_tooltip.scss
ui/app/styles/clinical/_diagnosis.scss
ui/app/styles/clinical/treatment/_treatment.scss
ui/test/unit/clinical/controllers/drugOrderHistoryController.spec.js
ui/test/unit/clinical/directives/cdssAlertRow.spec.js

Jira - https://bahmni.atlassian.net/browse/BS-58
- Trigger CDSS alerts and show active alerts in the diagnosis tab. Disable saving of critical alerts unless dismissed from the medications tab.

BS-58: Trigger and show CDSS Active alert alert at the diagnosis/conditions and Medications tab

---

ui/app/clinical/consultation/directives/tooltip.js
ui/app/clinical/consultation/views/orderSelector.html
ui/app/clinical/index.html

Jira - https://bahmni.atlassian.net/browse/BS-270
Added a tooltip on hover to the orders buttons to show the full text of the orders.

BS-270 Added a  tooltip to procedures buttons

---

ui/app/clinical/common/services/cdssService.js
ui/app/clinical/consultation/controllers/addTreatmentController.js
ui/app/clinical/consultation/controllers/diagnosisController.js
ui/app/common/displaycontrols/drugOrdersSection/directives/drugOrdersSection.js
ui/app/common/displaycontrols/drugOrdersSection/views/drugOrdersSection.html
ui/app/styles/bahmni-components/_tooltip.scss
ui/app/styles/clinical/treatment/_customDrugOrderHistory.scss
ui/app/styles/clinical/treatment/_treatment.scss
ui/app/styles/clinical/treatment/_treatmentOrderSet.scss
ui/test/unit/clinical/consultation/controllers/diagnosisController.spec.js
ui/test/unit/clinical/consultation/services/cdssService.spec.js
ui/test/unit/clinical/controllers/addTreatmentController.spec.js

Jira - https://bahmni.atlassian.net/browse/BS-14
Show alert(s) in the Medications Tab, when a drug order set contradicts with Diagnosis(es) or other saved/draft drugs.

BS-14 | Trigger CDSS on the Drug Order Sets

---

README.md
ui/app/admin/controllers/fhirExportController.js
ui/app/admin/services/fhirExportService.js
ui/app/clinical/common/services/cdssService.js
ui/app/clinical/consultation/controllers/addTreatmentController.js
ui/app/clinical/consultation/controllers/consultationController.js
ui/app/clinical/consultation/controllers/diagnosisController.js
ui/app/clinical/consultation/views/cdssAlertRow.html
ui/app/clinical/consultation/views/cdssPopover.html
ui/app/clinical/consultation/views/conditions.html
ui/app/clinical/consultation/views/diagnosis.html
ui/app/clinical/consultation/views/diagnosisRow.html
ui/app/styles/bahmni-components/_tooltip.scss
ui/app/styles/clinical/_diagnosis.scss
ui/test/unit/admin/controllers/fhirExportController.spec.js
ui/test/unit/clinical/consultation/controllers/diagnosisController.spec.js
ui/test/unit/clinical/consultation/services/cdssService.spec.js
ui/test/unit/clinical/controllers/addTreatmentController.spec.js

Resolved all the issues as part of bug bash - https://docs.google.com/spreadsheets/d/15AkI3q40VXMYW8S3lpqUf9CG2TdBSVAUE9qUr1enAXE/edit#gid=0

SNOMED phase2 bugs

---

ui/app/common/displaycontrols/observation/directives/bahmniObservation.js
ui/app/common/displaycontrols/observation/views/observationDisplayControl.html
ui/app/common/obs/directives/showObservation.js
ui/app/common/obs/views/showObservation.html

Configuration support in Obs display control ("displayNameType"), so that the concept name labels can be shown in FSN. If nothing specified default behavior of showing in SN (or FSN in SN is not available) is retained.
For example: 
`
"basicVitals": {
"translationKey": "XYZ",
"type": "observation",
"isObservation": true,
"displayOrder": 6,
"dashboardConfig": {
"conceptNames": [
"Height (cm)",
"Weight (kg)",
"Body mass index",
"BMI Status"
],
"showDetailsButton": true,
"numberOfVisits": 3,
"displayNameType": "FSN"
},
"hideEmptyDisplayControl": true
}
`
This also resolves the bug where in non-implementation locale usage by user (e,g. default locale = en, user locale = french), the obs display control would not show non-matching concept names, even though the API returned the right data.

BAH-3181 | Configuration support for concept name label to be shown on FSN if specified

---

ui/app/common/attributeTypes/views/attributeInformation.html
ui/app/common/displaycontrols/programs/directives/programs.js
ui/app/common/uicontrols/programmanagement/directive/programAttributes.js

[JIRA link](https://bahmni.atlassian.net/browse/BAH-3336?atlOrigin=eyJpIjoiMDlkNmJkZjY3MjY3NDVhNmI3ZTE1MDA3N2YxZDkxMjYiLCJwIjoiaiJ9)
The dropdowns shown in programs module were not showing the linked conceptSet post the OpenMRS upgrade. Changes at a UI level had to be made to support ConceptDataType in OpenMRS.

BAH-3336 | Patient Stage dropdown is empty in programs module [Env - Docker.standard]

---

ui/app/clinical/common/views/visitTabPrint.html

Removed the unwanted line breaks in visit tab print.
Before:
After:

BAH-3501 | Remove extra line breaks in visitTab print

---

ui/app/clinical/common/mappers/patientFileObservationsMapper.js
ui/app/common/domain/services/encounterService.js
ui/test/unit/clinical/mappers/patientFileObservationsMapper.spec.js
ui/test/unit/registration/services/encounterService.spec.js

As part of this PR, the patient documents widget is updated to show the document uploads of a patient in reverse chronological order.
This is achieved by passing the `order:desc` parameter to the `/openmrs/ws/rest/v1/encounter` GET api call.

BAH-3531 | Refactor. Show latest patient document uploads first

---

ui/app/clinical/common/views/visitSummary.html

JIRA -> [BAH-3523](https://bahmni.atlassian.net/browse/BAH-3523)
In this PR, we have reintroduced support for pacsOrder and radiology in the visit summary screen which was removed to align with the requirements of Bahmni Lite, which does not have PACS/radiology order configured.

BAH-3523 | Add. Pacs Orders and Radiology in Visit Summary Screen

---

ui/app/clinical/common/mappers/patientFileObservationsMapper.js

This PR fixes the sort order for patient document files with the same obs datetime. This is a patch PR for https://github.com/Bahmni/openmrs-module-bahmniapps/pull/836

BAH-3531 | Fix. Sort weight calculation for patient files with same Obsdatetime

---

ui/app/clinical/config/visitMandatoryTab.json
ui/app/clinical/displaycontrols/investigationresults/views/investigationChart.html

JIRA -> [BAH-3532](https://bahmni.atlassian.net/browse/BAH-3532)
This PR renames the `hideVisitDate` control to `hideResultsColumn` for improved clarity. The `hideResultsColumn` control is responsible for concealing the display of lab order results.
hideResultsColumn : true           |  hideResultsColumn : false
:-------------------------:|:-------------------------:

BAH-3532 | Refactor. Rename hideVisitDate -> hideResultsColumn

---

ui/app/styles/registration/_registration.scss

In registration second page: The lengthy Z Score comment text is fixed.
Asana Link: https://app.asana.com/0/1204322126657135/1205585485493098/f

Fix css for zscore lengthy text in registration 2nd page

---

ui/app/clinical/displaycontrols/investigationresults/directives/investigationResults.js
ui/app/clinical/displaycontrols/investigationresults/models/tabularLabOrderResults.js
ui/app/clinical/displaycontrols/investigationresults/services/labOrderResultService.js
ui/app/clinical/displaycontrols/investigationresults/views/investigationChart.html
ui/app/clinical/displaycontrols/investigationresults/views/investigationTableRow.html
ui/app/styles/clinical/_visit.scss
ui/test/unit/clinical/services/labOrderResultService.spec.js

JIRA -> [BAH-3606](https://bahmni.atlassian.net/browse/BAH-3606)
In this PR, I have added a configuration to  group tests by panels and to display it in the investigation chart view. Also, removed the logic for sorting lab test by name since we decided to go with sorting based on sortWeight, it is no longer needed.

BAH-3606 | Add. Panel Based Grouping Of Tests In Investigation Chart View

---

ui/app/clinical/dashboard/controllers/patientDashboardTreatmentController.js

In docker standard environment prescription print header is showing IdentifierSourceName in print Header instead of referring to PrintHeader.This works fine in docker lite environment as we do not have as we do not have IdentifierSourceName attribute in locations in lite environment it always refers to print header properly.

Deepthi M|BAH-3581| Fixed the issue with Identifier being loaded on the print Header in docker standard env.

---

.github/workflows/build_publish.yml

JIRA -> [BAH-3644](https://bahmni.atlassian.net/browse/BAH-3644)
In this PR, an workflow based event trigger has been added to the Build and Publish [openmrs-module-bahmniapps](https://github.com/Bahmni/openmrs-module-bahmniapps) workflow. The Build and Publish openmrs-module-bahmniapps workflow was not getting triggered as the commit action in the Pull Translations From Transifex workflow run can’t trigger a new workflow run [(Refer comment)](https://github.com/orgs/community/discussions/27028#discussioncomment-3254360). The changes added will programmatically trigger Build and Publish openmrs-module-bahmniapps once the Pull Translations From Transifex workflow is successfully completed.

BAH-3644 | Add. Event Trigger To Publish Image

---

ui/app/clinical/consultation/controllers/addTreatmentController.js
ui/app/clinical/consultation/controllers/drugOrderHistoryController.js
ui/app/clinical/consultation/directives/newDrugOrders.js
ui/app/clinical/consultation/views/newDrugOrders.html
ui/app/clinical/consultation/views/treatmentSections/drugOrderHistory.html
ui/app/i18n/clinical/locale_en.json
ui/test/unit/clinical/controllers/drugOrderHistoryController.spec.js

This PR has changes to show or hide IPD button in the treatments display control. Earlier, enableIPDFeature was used as common config to hide IPD button and the IPD dashboard. As part of this change 
- any medication added in an IPD visit will be considered as IPD medication and OPD medication if added in an OPD visit
- A text will be shown in each tile of treatment (already prescribed and new) to indicate whether it is an IPD or OPD medication

Arjun | To hide show/hide IPD button in treatments tab

---

ui/app/clinical/common/controllers/visitController.js
ui/app/common/displaycontrols/admissiondetails/directives/admissionDetails.js
ui/app/common/displaycontrols/diagnosis/directives/bahmniDiagnosis.js
ui/app/common/displaycontrols/observation/directives/bahmniObservation.js
ui/app/common/displaycontrols/prescription/directives/prescription.js
ui/app/common/obs/directives/showObservation.js
ui/app/common/ui-helper/printer.js

JIRA Card -> [https://bahmni.atlassian.net/browse/BAH-3244](https://bahmni.atlassian.net/browse/BAH-3244)

Kavitha | BAH-3244 | adds printing based on custom templates and configs

---

ui/Gruntfile.js

JIRA - https://bahmni.atlassian.net/browse/BAH-3701
The Next-Ui CSS changes were built and packaged in micro-frontend dist folder but was not added to the bahmni-web build. Due to this, CSS for Next-Ui was broken.

BAH-3701 | Package Next-Ui minified CSS in Gruntfile

---

.github/workflows/build_publish.yml
.github/workflows/validate_pr.yml
README.md

JIRA -> https://bahmni.atlassian.net/browse/BAH-3923
The Bahmniapps workflow was failing because the installed version of RubyGems (2.7.6.3) was too old to support the required version of the ffi gem for Compass. To resolve this issue, RubyGems needed to be updated to a version meeting the minimum requirement for ffi (>= 3.3.22). For this, the Ruby version had to be upgraded to greater than 3. Therefore, the Ruby version has been upgraded to 3.1.

Fix. Upgrade Ruby Version

---

ui/app/clinical/dashboard/services/clinicalDashboardConfig.js

JIRA -> [BAH-3983](https://bahmni.atlassian.net/browse/BAH-3983)
The IPD Dashboard Tab was originally added to display the IPD Dashboard, which was later added as a micro frontend, replacing the need for this tab. In this PR, the broken IPD Dashboard Tab has been removed.

BAH-3983 | Fix. Remove Broken IPD Tab in Clinical

---

ui/app/i18n/adt/locale_en.json
ui/app/i18n/ipd/locale_en.json

JIRA -> [BAH-4009](https://bahmni.atlassian.net/browse/BAH-4009)
In this PR, missing translations for certain labels in the Admission Details display control has been added back in. Specifically, the `DISCHARGE_DATE_LABEL` and `DAYS_ADMITTED_MESSAGE` were not translated and are showing the placeholder text instead.
|Fixed Bed management Screen|Fixed ADT Screen|
|-|-|
|![Screenshot 2024-07-09 at 9 18 20 AM](https://github.com/Bahmni/openmrs-module-bahmniapps/assets/121226043/d91146cb-3f8e-401f-92cc-b903a2ccf87a)|![Screenshot 2024-07-09 at 9 18 37 AM](https://github.com/Bahmni/openmrs-module-bahmniapps/assets/121226043/fc4e2ef1-571e-4a01-896c-cb094e39d383)|

BAH-4009 | Add. Missing Translations In Bed, ADT

---

ui/app/common/concept-set/services/conceptGroupFormatService.js
ui/test/unit/common/concept-set/services/conceptGroupFormatService.spec.js

Jira -> [BAH-4012](https://bahmni.atlassian.net/browse/BAH-4012)
This PR aims to resolve the Abnormal boolean values associated with a vital from getting displayed on the Consultation tab.
| Issue observed | After the fix |
|-|-|
|<img width="960" alt="Screenshot 2024-07-10 at 8 37 42 AM" src="https://github.com/Bahmni/openmrs-module-bahmniapps/assets/121226043/138515b9-b150-4709-ab89-47798b073505">|<img width="960" alt="Screenshot 2024-07-10 at 8 50 02 AM" src="https://github.com/Bahmni/openmrs-module-bahmniapps/assets/121226043/d90b603e-d88f-49dd-822b-f2f143642d39">|

BAH-4012 | Fix. Abnormal Value Getting Displayed In Consultation Tab

---

ui/app/admin/initialization.js
ui/app/adt/initialization.js
ui/app/bedmanagement/initialization.js
ui/app/clinical/initialization.js
ui/app/common/auth/authentication.js
ui/app/document-upload/initialization.js
ui/app/home/initialization.js
ui/app/orders/initialization.js
ui/app/ot/initialization.js
ui/app/registration/initialization.js
ui/app/reports/initialization.js

JIRA -> [BAH-3971](https://bahmni.atlassian.net/browse/BAH-3971)
This pull request introduces context support between logout and re-login for all Bahmni apps modules. This feature is enabled when the global property `contextcookieexpirationtimeinminutes` is set to a non-null positive integer. When this property is set, the page from which the user logs out will be stored in the context, and upon re-login, the user will be redirected to the same page.

BAH-3971 | Add. Context Between Logout and Re-Login for All Bahmni Modules

---

ui/app/ot/helpers/surgicalAppointmentHelper.js
ui/test/unit/ot/helpers/surgicalAppointmentHelper.spec.js

This PR adds a condition to show all the providers with a display name in the OT module when the `primarySurgeonsForOT` configuration is either empty or undefined

BAH-4053 | FIx. Add condition to show all providers in OT when a filter config is not passed.

---

ui/app/clinical/common/controllers/visitController.js

This PR removes the filter for IPD visit while setting readMode, due to which IPD Dashboard breaks and shows invalid dates when a patient is admitted from visit other than IPD.
| Before Fix | After Fix |
|--------|--------|
| <img width="1542" alt="image" src="https://github.com/user-attachments/assets/ceeb8aa1-4b28-45e4-9ae3-1ef3dc62f486">   | <img width="1531" alt="image" src="https://github.com/user-attachments/assets/14a0496d-8bbb-4bb1-a038-5686351f510b"> |

BAH-3845 | Fix. Remove filter for IPD Visit while opening IPD Visit

---

ui/app/clinical/consultation/views/treatmentSections/drugOrderHistory.html

JIRA -> [BAH-4049](https://bahmni.atlassian.net/browse/BAH-4049)
As part of the print medication feature, a configuration was introduced to auto select all medications in the medications tab for printing. However, this configuration is currently not functioning. The issue arose due to the merging of a PR for enabling the IPD feature, which inadvertently removed few changes related to print medication feature https://github.com/Bahmni/openmrs-module-bahmniapps/pull/959/files#diff-b66de7a8ea826627711d635700e677262b8918a366bdd54947eb80f746255b68R9. This PR adds those changes back to restore the complete functionality of the print medication feature.

BAH-4049 | Fix. Auto Select Feature for Print Medication Feature

---

ui/app/clinical/consultation/models/visitHistoryEntry.js
ui/app/clinical/displaycontrols/allvisits/directives/visitsTable.js
ui/app/clinical/displaycontrols/allvisits/views/visitsTable.html
ui/app/common/displaycontrols/navigationlinks/directives/navigationLinks.js
ui/app/i18n/clinical/locale_en.json

JIRA -> [BAH-4064](https://bahmni.atlassian.net/browse/BAH-4064)
In this PR aims to revert the recent changes made to the patient dashboard that open the IPD dashboard when the active visit link is clicked. This change breaks the existing patient dashboard flow and is not backward compatible. Instead, introduce a new link in the links tile that, when clicked, takes the user to the IPD dashboard for the current patient. The link will be enabled only when the `enableIPDFeature` config is set to true in openmrs/apps/clinical/app.json.

BAH-4064 | Refactor. IPD Dashboard Link Position

---

ui/app/adt/controllers/adtController.js
ui/app/adt/controllers/careViewController.js
ui/app/bedmanagement/controllers/careViewController.js
ui/app/clinical/common/controllers/visitController.js
ui/test/unit/adt/controllers/careViewController.spec.js
ui/test/unit/bedmanagement/controllers/careViewController.spec.js

This PR adds changes to pass the currentUser information to the IPD Dashboard scope through `hostData`

BAH-4062 | Add. Pass currentUser to IPD Dashboard scope

---

micro-frontends/src/next-ui/Components/ProviderNotificationPatients/PatientListContent.jsx
ui/test/unit/common/uicontrols/programmanagement/controllers/manageProgramController.spec.js

https://app.asana.com/0/1204322126657135/1208406174218905

A-1208406174218905 | Duplicate notification entries displayed in tab

---

ui/app/clinical/dashboard/views/dashboardSections/flowSheet.html
ui/app/common/displaycontrols/pivottable/views/pivotTable.html

https://app.asana.com/0/1204322126657135/1208511162281418

A-1208511162281418 | Translation capability to flowsheets

---

ui/app/styles/registration/_registration.scss

This PR fixes the responsiveness issue with the extension iframe that is shown from the Patient Registration for linking external identifiers.
JIRA: https://bahmni.atlassian.net/browse/BAH-4118
Before:
After:

BAH-4118 | Fix. Extension Iframe height to be responsive

---

ui/Gruntfile.js
ui/app/clinical/index.html
ui/package.json
ui/yarn.lock

Replaced CDN links for html2pdf.js, pdfmake, html2canvas, marked, and Jitsi’s external_api.js with local dependencies in package.json, and updated Gruntfile to include them. This resolves >1min load time in on-premise deployment without internet. Refs PRs #326, #520, #768."

"BAH-3841| Fix slow clinical module load by adding dependencies locally"
